/**
 * Save face as talent keeps the rights gate across the copy and FAILS CLOSED
 * (#2018): the branch table in `decideFace`, one case per row, then the two
 * branches that proceed end to end.
 */

import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { ScopedDb } from '@/platform/server/db/scoped';
import { AttestationRequiredError } from '@/platform/errors';
import { asStub } from '@/test/as-stub';

const requireUploadRights = vi.fn();
const carryUploadRights = vi.fn(async () => undefined);
const enqueueLibraryTalentSheet = vi.fn(async () => 'run-1');

vi.doMock('@/cast/server/upload-rights', () => ({
  requireUploadRights,
  carryUploadRights,
}));
vi.doMock('./enqueue-library-talent-sheet', () => ({
  enqueueLibraryTalentSheet,
}));

const { decideFace, saveCharacterFaceAsTalent, talentSheetStoragePath } =
  await import('./save-character-face');

const UPLOAD_URL = '/r2/sequences/team-1/uploads/mia.png';
const GEN_URL = '/r2/sheets/gen.png';
const character = {
  id: 'char-1',
  name: 'Mia',
  characterId: 'mia',
  physicalDescription: 'tall, red hair',
  selectedSheetVersionId: 'sheet-1',
  sheetImageUrl: UPLOAD_URL,
  talentId: null as string | null,
  talent: null as { name: string } | null,
  age: '',
  gender: '',
  ethnicity: '',
  standardClothing: '',
  distinguishingFeatures: '',
  personality: '',
  movement: '',
  voiceDescription: '',
  voiceOnly: false,
  isPerson: true,
  consistencyTag: 'mia',
  looks: [],
};

type Sheet = {
  url: string | null;
  workflowRunId: string | null;
  bibleVersionId: string | null;
};
const upload = (): Sheet => ({
  url: UPLOAD_URL,
  workflowRunId: null,
  bibleVersionId: 'bible-1',
});
const generated = (bibleVersionId: string | null = 'bible-1'): Sheet => ({
  url: GEN_URL,
  workflowRunId: 'run-9',
  bibleVersionId,
});

const talentCreate = vi.fn(async (row: { isHuman: boolean }) => ({
  id: 'tal-1',
  name: 'Mia',
  description: 'tall, red hair',
  ...row,
}));

function scopedDb(
  sheet: Sheet | null,
  opts: {
    cast?: Partial<typeof character>;
    /** The talent the sheet's bible version names, when a run drew it. */
    versionTalentId?: string | null;
  } = {}
): ScopedDb {
  // stub covering only what saveCharacterFaceAsTalent reads
  return asStub<ScopedDb>({
    sequences: { getForUser: vi.fn(async () => ({ id: 'seq-1' })) },
    characters: {
      getById: vi.fn(async () => ({ ...character, ...opts.cast })),
      getBibleVersion: vi.fn(async () => ({
        talentId: opts.versionTalentId ?? null,
      })),
    },
    characterSheetVariants: { getById: vi.fn(async () => sheet) },
    talent: { create: talentCreate },
  });
}

const ctx = { userId: 'u1', teamId: 'team-1' };
const args = { sequenceId: 'seq-1', characterId: 'char-1' };

beforeEach(() => {
  vi.clearAllMocks();
});

describe('decideFace: the branch table (default refuses)', () => {
  const cases: Array<{
    name: string;
    sheet: Sheet | null;
    opts?: Parameters<typeof scopedDb>[1];
    expect: { kind: string; reason?: RegExp };
  }> = [
    {
      name: 'character cast with a talent, sheet reused from it',
      sheet: upload(),
      opts: { cast: { talentId: 'tal-0', talent: { name: 'Sienna' } } },
      expect: { kind: 'refused', reason: /already talent Sienna/ },
    },
    {
      name: 'character cast with a human talent, sheet generated from it',
      sheet: generated(),
      opts: {
        cast: { talentId: 'tal-0', talent: { name: 'Sienna' } },
        versionTalentId: 'tal-0',
      },
      expect: { kind: 'refused', reason: /already talent Sienna/ },
    },
    {
      name: 'no selected sheet',
      sheet: null,
      expect: { kind: 'refused', reason: /no sheet yet/ },
    },
    {
      name: 'selected sheet with no image',
      sheet: { url: null, workflowRunId: 'run-9', bibleVersionId: 'bible-1' },
      expect: { kind: 'refused', reason: /no sheet yet/ },
    },
    {
      name: 'generated by our run from a bible version with no talent',
      sheet: generated(),
      expect: { kind: 'generated' },
    },
    {
      name: 'generated by our run from a bible version that named a talent (recast away since)',
      sheet: generated(),
      opts: { versionTalentId: 'tal-0' },
      expect: { kind: 'refused', reason: /drawn from a talent/ },
    },
    {
      name: 'generated by our run, bible version unknown (pre-#1600 row)',
      sheet: generated(null),
      expect: { kind: 'refused', reason: /which version/ },
    },
    {
      name: 'upload (UI finalize or MCP set_character_sheet_from_upload)',
      sheet: upload(),
      expect: { kind: 'ledger' },
    },
    {
      name: 'unknown provenance: a model string but no run',
      sheet: { url: GEN_URL, workflowRunId: null, bibleVersionId: 'bible-1' },
      expect: { kind: 'ledger' },
    },
    {
      name: 'backfilled, copied or pre-#1419 row (no run, no bible version)',
      sheet: { url: GEN_URL, workflowRunId: null, bibleVersionId: null },
      expect: { kind: 'ledger' },
    },
  ];

  for (const c of cases) {
    it(c.name, async () => {
      const db = scopedDb(c.sheet, c.opts);
      const decision = await decideFace(db, {
        ...character,
        ...c.opts?.cast,
      });
      expect(decision.kind).toBe(c.expect.kind);
      if (c.expect.reason && decision.kind === 'refused') {
        expect(decision.reason).toMatch(c.expect.reason);
      }
    });
  }
});

describe('saveCharacterFaceAsTalent', () => {
  it('ledger branch, real person signed: the talent is human and its sheet URL is covered before the run', async () => {
    requireUploadRights.mockResolvedValue(
      new Map([[UPLOAD_URL, { depictsRealPerson: true }]])
    );

    const result = await saveCharacterFaceAsTalent(
      scopedDb(upload()),
      ctx,
      args
    );

    expect(talentCreate).toHaveBeenCalledWith(
      expect.objectContaining({ isHuman: true })
    );
    const [, from, to] = carryUploadRights.mock.calls[0] ?? [];
    const sheetId = asStub<{ sheetId: string }>(
      enqueueLibraryTalentSheet.mock.calls[0]?.[1]
    ).sheetId;
    expect(from).toBe(UPLOAD_URL);
    expect(to).toContain(talentSheetStoragePath('team-1', 'tal-1', sheetId));
    expect(carryUploadRights.mock.invocationCallOrder[0]).toBeLessThan(
      enqueueLibraryTalentSheet.mock.invocationCallOrder[0] ?? 0
    );
    expect(enqueueLibraryTalentSheet.mock.calls[0]?.[1]).toMatchObject({
      talentId: 'tal-1',
      activity: 'portrait',
      workflowInput: expect.objectContaining({ uploadedSheetUrl: UPLOAD_URL }),
    });
    expect(result.runId).toBe('run-1');
  });

  it('ledger branch, cleared (no person): the talent is an AI face and the row still carries', async () => {
    requireUploadRights.mockResolvedValue(
      new Map([[UPLOAD_URL, { depictsRealPerson: false }]])
    );
    await saveCharacterFaceAsTalent(scopedDb(upload()), ctx, args);
    expect(talentCreate).toHaveBeenCalledWith(
      expect.objectContaining({ isHuman: false })
    );
    expect(carryUploadRights).toHaveBeenCalledTimes(1);
  });

  it('ledger branch, no row (or unsigned real person): refused before any row is written', async () => {
    requireUploadRights.mockRejectedValue(
      new AttestationRequiredError(
        'This image has not been checked for a real person yet'
      )
    );

    await expect(
      saveCharacterFaceAsTalent(scopedDb(upload()), ctx, args)
    ).rejects.toBeInstanceOf(AttestationRequiredError);
    expect(talentCreate).not.toHaveBeenCalled();
    expect(carryUploadRights).not.toHaveBeenCalled();
    expect(enqueueLibraryTalentSheet).not.toHaveBeenCalled();
  });

  it('generated branch: AI face, no ledger', async () => {
    await saveCharacterFaceAsTalent(scopedDb(generated()), ctx, args);

    expect(requireUploadRights).not.toHaveBeenCalled();
    expect(carryUploadRights).not.toHaveBeenCalled();
    expect(talentCreate).toHaveBeenCalledWith(
      expect.objectContaining({ isHuman: false })
    );
  });

  it('a refused decision throws and writes nothing', async () => {
    await expect(
      saveCharacterFaceAsTalent(
        scopedDb(generated(), { versionTalentId: 'tal-0' }),
        ctx,
        args
      )
    ).rejects.toThrow(/drawn from a talent/);
    expect(talentCreate).not.toHaveBeenCalled();
    expect(requireUploadRights).not.toHaveBeenCalled();
  });
});
