reviews:
  enabled: true            
  drafts: true             
  simple_changes: true     
  branches:
    include:
      - "*"
  paths:
    include:
      - "**"
    exclude: []
comments:
  summary: true
  code_suggestions: true