-- #1419 PR C2 — drop the duplicated sheet/reference mirror columns.
--
-- Generated by `bun db:generate` from the schema edit; the SQL below is
-- drizzle-kit's, not hand-written. `scripts/check-migrations.ts` flags
-- `ALTER TABLE … DROP COLUMN`, so this was committed with --allow-destructive.
--
-- Safe to run destructively, in this order:
--   * PR A (20260901073033 / 073039) copied every one of these values into a
--     `character_sheet_variants` / `location_sheet_variants` row. Verified on
--     production: 0 orphan mirrors, and 0 rows resolving a different url or
--     input hash than the column held.
--   * PR B (#1421) made every scoped read resolve the four fields from the
--     live version via COALESCE(selected_..._version_id, <parent>.id).
--   * PR C1 (#1422) stopped every write. It is deployed BEFORE this migration
--     applies, which is why the drop is a separate PR: migrations run ahead of
--     `wrangler deploy`, so shipping both together would leave the old worker
--     writing to columns that no longer exist.
--
-- `sheetStatus` / `sheetError` and their location twins deliberately survive.
-- They are generation lifecycle, stamped when no variant row exists yet, not
-- mirrors of the version row — the same call #1067 made for frames.imageStatus.
--
-- SQLite/D1 support DROP COLUMN natively, so there is no table rebuild and the
-- #612 inbound-CASCADE trap does not apply.

ALTER TABLE `characters` DROP COLUMN `sheet_image_url`;--> statement-breakpoint
ALTER TABLE `characters` DROP COLUMN `sheet_image_path`;--> statement-breakpoint
ALTER TABLE `characters` DROP COLUMN `sheet_generated_at`;--> statement-breakpoint
ALTER TABLE `characters` DROP COLUMN `sheet_input_hash`;--> statement-breakpoint
ALTER TABLE `sequence_locations` DROP COLUMN `reference_image_url`;--> statement-breakpoint
ALTER TABLE `sequence_locations` DROP COLUMN `reference_image_path`;--> statement-breakpoint
ALTER TABLE `sequence_locations` DROP COLUMN `reference_generated_at`;--> statement-breakpoint
ALTER TABLE `sequence_locations` DROP COLUMN `reference_input_hash`;