// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema and codec mapping for motion models

import { z } from 'zod';

import { motionTransform } from './motion-transform';

import {
  zGeminiOmni11FlashImageToVideoInput,
  zGeminiOmni11FlashInput,
  zGeminiOmni11FlashReferenceToVideoInput,
  zGrokImagineVideoV15ImageToVideoInput,
  zH3MaxImageToVideoInput,
  zH3MaxReferenceToVideoInput,
  zH3MaxTextToVideoInput,
  zKlingVideoO3ProReferenceToVideoInput,
  zKlingVideoO3ProTextToVideoInput,
  zKlingVideoV3ProImageToVideoInput,
  zSeedance20EnterpriseV2ImageToVideoInput,
  zSeedance20EnterpriseV2ReferenceToVideoInput,
  zSeedance20EnterpriseV2TextToVideoInput,
  zSeedance20MiniImageToVideoInput,
  zSeedance20MiniReferenceToVideoInput,
  zSeedance20MiniTextToVideoInput,
  zSeedance25ImageToVideoInput,
  zSeedance25ReferenceToVideoInput,
  zSeedance25TextToVideoInput,
} from '@/motion/server/generated/zod.gen';

import {
  GeminiOmni11FlashImageToVideoInputSchema,
  GeminiOmni11FlashInputSchema,
  GeminiOmni11FlashReferenceToVideoInputSchema,
  GrokImagineVideoV15ImageToVideoInputSchema,
  H3MaxImageToVideoInputSchema,
  H3MaxReferenceToVideoInputSchema,
  H3MaxTextToVideoInputSchema,
  KlingVideoO3ProReferenceToVideoInputSchema,
  KlingVideoO3ProTextToVideoInputSchema,
  KlingVideoV3ProImageToVideoInputSchema,
  Seedance20EnterpriseV2ImageToVideoInputSchema,
  Seedance20EnterpriseV2ReferenceToVideoInputSchema,
  Seedance20EnterpriseV2TextToVideoInputSchema,
  Seedance20MiniImageToVideoInputSchema,
  Seedance20MiniReferenceToVideoInputSchema,
  Seedance20MiniTextToVideoInputSchema,
  Seedance25ImageToVideoInputSchema,
  Seedance25ReferenceToVideoInputSchema,
  Seedance25TextToVideoInputSchema,
} from '@/motion/server/generated/schemas.gen';

export type MotionJSONSchema =
  | typeof GeminiOmni11FlashImageToVideoInputSchema
  | typeof GeminiOmni11FlashInputSchema
  | typeof GeminiOmni11FlashReferenceToVideoInputSchema
  | typeof GrokImagineVideoV15ImageToVideoInputSchema
  | typeof H3MaxImageToVideoInputSchema
  | typeof H3MaxReferenceToVideoInputSchema
  | typeof H3MaxTextToVideoInputSchema
  | typeof KlingVideoO3ProReferenceToVideoInputSchema
  | typeof KlingVideoO3ProTextToVideoInputSchema
  | typeof KlingVideoV3ProImageToVideoInputSchema
  | typeof Seedance20EnterpriseV2ImageToVideoInputSchema
  | typeof Seedance20EnterpriseV2ReferenceToVideoInputSchema
  | typeof Seedance20EnterpriseV2TextToVideoInputSchema
  | typeof Seedance20MiniImageToVideoInputSchema
  | typeof Seedance20MiniReferenceToVideoInputSchema
  | typeof Seedance20MiniTextToVideoInputSchema
  | typeof Seedance25ImageToVideoInputSchema
  | typeof Seedance25ReferenceToVideoInputSchema
  | typeof Seedance25TextToVideoInputSchema;

export const MOTION_INPUT_SCHEMAS = {
  'bytedance/seedance-2.0/enterprise/v2/image-to-video':
    zSeedance20EnterpriseV2ImageToVideoInput,
  'bytedance/seedance-2.0/enterprise/v2/reference-to-video':
    zSeedance20EnterpriseV2ReferenceToVideoInput,
  'bytedance/seedance-2.0/enterprise/v2/text-to-video':
    zSeedance20EnterpriseV2TextToVideoInput,
  'bytedance/seedance-2.0/mini/image-to-video':
    zSeedance20MiniImageToVideoInput,
  'bytedance/seedance-2.0/mini/reference-to-video':
    zSeedance20MiniReferenceToVideoInput,
  'bytedance/seedance-2.0/mini/text-to-video': zSeedance20MiniTextToVideoInput,
  'bytedance/seedance-2.5/image-to-video': zSeedance25ImageToVideoInput,
  'bytedance/seedance-2.5/reference-to-video': zSeedance25ReferenceToVideoInput,
  'bytedance/seedance-2.5/text-to-video': zSeedance25TextToVideoInput,
  'fal-ai/gemini-omni-1.1-flash': zGeminiOmni11FlashInput,
  'fal-ai/gemini-omni-1.1-flash/image-to-video':
    zGeminiOmni11FlashImageToVideoInput,
  'fal-ai/gemini-omni-1.1-flash/reference-to-video':
    zGeminiOmni11FlashReferenceToVideoInput,
  'fal-ai/kling-video/o3/pro/reference-to-video':
    zKlingVideoO3ProReferenceToVideoInput,
  'fal-ai/kling-video/o3/pro/text-to-video': zKlingVideoO3ProTextToVideoInput,
  'fal-ai/kling-video/v3/pro/image-to-video': zKlingVideoV3ProImageToVideoInput,
  'minimax/h3-max/image-to-video': zH3MaxImageToVideoInput,
  'minimax/h3-max/reference-to-video': zH3MaxReferenceToVideoInput,
  'minimax/h3-max/text-to-video': zH3MaxTextToVideoInput,
  'xai/grok-imagine-video/v1.5/image-to-video':
    zGrokImagineVideoV15ImageToVideoInput,
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

/**
 * Input payload for a given motion endpoint. Generated API surface — kept
 * exported even while unused so consumers of new endpoints can adopt it.
 * @public
 */
export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;

export const MOTION_JSON_SCHEMAS = {
  'bytedance/seedance-2.0/enterprise/v2/image-to-video':
    Seedance20EnterpriseV2ImageToVideoInputSchema,
  'bytedance/seedance-2.0/enterprise/v2/reference-to-video':
    Seedance20EnterpriseV2ReferenceToVideoInputSchema,
  'bytedance/seedance-2.0/enterprise/v2/text-to-video':
    Seedance20EnterpriseV2TextToVideoInputSchema,
  'bytedance/seedance-2.0/mini/image-to-video':
    Seedance20MiniImageToVideoInputSchema,
  'bytedance/seedance-2.0/mini/reference-to-video':
    Seedance20MiniReferenceToVideoInputSchema,
  'bytedance/seedance-2.0/mini/text-to-video':
    Seedance20MiniTextToVideoInputSchema,
  'bytedance/seedance-2.5/image-to-video': Seedance25ImageToVideoInputSchema,
  'bytedance/seedance-2.5/reference-to-video':
    Seedance25ReferenceToVideoInputSchema,
  'bytedance/seedance-2.5/text-to-video': Seedance25TextToVideoInputSchema,
  'fal-ai/gemini-omni-1.1-flash': GeminiOmni11FlashInputSchema,
  'fal-ai/gemini-omni-1.1-flash/image-to-video':
    GeminiOmni11FlashImageToVideoInputSchema,
  'fal-ai/gemini-omni-1.1-flash/reference-to-video':
    GeminiOmni11FlashReferenceToVideoInputSchema,
  'fal-ai/kling-video/o3/pro/reference-to-video':
    KlingVideoO3ProReferenceToVideoInputSchema,
  'fal-ai/kling-video/o3/pro/text-to-video':
    KlingVideoO3ProTextToVideoInputSchema,
  'fal-ai/kling-video/v3/pro/image-to-video':
    KlingVideoV3ProImageToVideoInputSchema,
  'minimax/h3-max/image-to-video': H3MaxImageToVideoInputSchema,
  'minimax/h3-max/reference-to-video': H3MaxReferenceToVideoInputSchema,
  'minimax/h3-max/text-to-video': H3MaxTextToVideoInputSchema,
  'xai/grok-imagine-video/v1.5/image-to-video':
    GrokImagineVideoV15ImageToVideoInputSchema,
} satisfies Record<MotionEndpointId, MotionJSONSchema>;

export const MOTION_TRANSFORMS = {
  'bytedance/seedance-2.0/enterprise/v2/image-to-video': motionTransform(
    zSeedance20EnterpriseV2ImageToVideoInput,
    Seedance20EnterpriseV2ImageToVideoInputSchema
  ),
  'bytedance/seedance-2.0/enterprise/v2/reference-to-video': motionTransform(
    zSeedance20EnterpriseV2ReferenceToVideoInput,
    Seedance20EnterpriseV2ReferenceToVideoInputSchema
  ),
  'bytedance/seedance-2.0/enterprise/v2/text-to-video': motionTransform(
    zSeedance20EnterpriseV2TextToVideoInput,
    Seedance20EnterpriseV2TextToVideoInputSchema
  ),
  'bytedance/seedance-2.0/mini/image-to-video': motionTransform(
    zSeedance20MiniImageToVideoInput,
    Seedance20MiniImageToVideoInputSchema
  ),
  'bytedance/seedance-2.0/mini/reference-to-video': motionTransform(
    zSeedance20MiniReferenceToVideoInput,
    Seedance20MiniReferenceToVideoInputSchema
  ),
  'bytedance/seedance-2.0/mini/text-to-video': motionTransform(
    zSeedance20MiniTextToVideoInput,
    Seedance20MiniTextToVideoInputSchema
  ),
  'bytedance/seedance-2.5/image-to-video': motionTransform(
    zSeedance25ImageToVideoInput,
    Seedance25ImageToVideoInputSchema
  ),
  'bytedance/seedance-2.5/reference-to-video': motionTransform(
    zSeedance25ReferenceToVideoInput,
    Seedance25ReferenceToVideoInputSchema
  ),
  'bytedance/seedance-2.5/text-to-video': motionTransform(
    zSeedance25TextToVideoInput,
    Seedance25TextToVideoInputSchema
  ),
  'fal-ai/gemini-omni-1.1-flash': motionTransform(
    zGeminiOmni11FlashInput,
    GeminiOmni11FlashInputSchema
  ),
  'fal-ai/gemini-omni-1.1-flash/image-to-video': motionTransform(
    zGeminiOmni11FlashImageToVideoInput,
    GeminiOmni11FlashImageToVideoInputSchema
  ),
  'fal-ai/gemini-omni-1.1-flash/reference-to-video': motionTransform(
    zGeminiOmni11FlashReferenceToVideoInput,
    GeminiOmni11FlashReferenceToVideoInputSchema
  ),
  'fal-ai/kling-video/o3/pro/reference-to-video': motionTransform(
    zKlingVideoO3ProReferenceToVideoInput,
    KlingVideoO3ProReferenceToVideoInputSchema
  ),
  'fal-ai/kling-video/o3/pro/text-to-video': motionTransform(
    zKlingVideoO3ProTextToVideoInput,
    KlingVideoO3ProTextToVideoInputSchema
  ),
  'fal-ai/kling-video/v3/pro/image-to-video': motionTransform(
    zKlingVideoV3ProImageToVideoInput,
    KlingVideoV3ProImageToVideoInputSchema
  ),
  'minimax/h3-max/image-to-video': motionTransform(
    zH3MaxImageToVideoInput,
    H3MaxImageToVideoInputSchema
  ),
  'minimax/h3-max/reference-to-video': motionTransform(
    zH3MaxReferenceToVideoInput,
    H3MaxReferenceToVideoInputSchema
  ),
  'minimax/h3-max/text-to-video': motionTransform(
    zH3MaxTextToVideoInput,
    H3MaxTextToVideoInputSchema
  ),
  'xai/grok-imagine-video/v1.5/image-to-video': motionTransform(
    zGrokImagineVideoV15ImageToVideoInput,
    GrokImagineVideoV15ImageToVideoInputSchema
  ),
};
