/**
 * Zod transform factory for motion model inputs.
 *
 * Creates a schema that accepts our internal camelCase format
 * (numeric duration, imageUrl, aspectRatio) and transforms it to
 * the API's snake_case format with correctly-typed duration values,
 * then validates with the generated Zod schema.
 *
 * All formatting rules are derived from the JSON Schema (generated by
 * @hey-api/schemas) — no Zod introspection needed.
 */

import { z } from 'zod';

import type { MotionJSONSchema } from './endpoint-map';

import { assertPromptWithinHardLimit } from '@/models/prompt-length';

// ---------------------------------------------------------------------------
// JSON Schema readers
// ---------------------------------------------------------------------------

type JSONProp = Record<string, unknown>;

/** Unwrap anyOf wrapper to find a variant matching a key. */
function unwrapAnyOf(prop: JSONProp, key: string): JSONProp | undefined {
  if (key in prop) return prop;
  if ('anyOf' in prop && Array.isArray(prop.anyOf)) {
    return prop.anyOf.find((s) => key in s);
  }
  return undefined;
}

/** Extract valid duration values from the JSON Schema duration property. */
export function getDurationValues<T extends MotionJSONSchema>(
  schema: T
): (string | number)[] {
  const props = schema.properties;
  if (!('duration' in props)) return [];
  const dur = props.duration as JSONProp;

  const withEnum = unwrapAnyOf(dur, 'enum');
  if (withEnum && Array.isArray(withEnum.enum))
    return withEnum.enum.filter((v) => !Number.isNaN(numericOf(v)));

  const withRange = unwrapAnyOf(dur, 'minimum');
  if (withRange) {
    const min = Number(withRange.minimum);
    const max = Number(withRange.maximum);
    return Array.from({ length: max - min + 1 }, (_, i) => min + i);
  }

  return [];
}

/**
 * Extract maxLength from the prompt property, handling anyOf wrappers.
 *
 * Present = fal enforces it, so it is a hard ceiling (#1754). Absent — every
 * Seedance endpoint — means there is no cap to enforce.
 */
function getPromptMaxLength(schema: MotionJSONSchema): number | undefined {
  const props = schema.properties;
  if (!('prompt' in props)) return undefined;
  const max = unwrapAnyOf(props.prompt, 'maxLength')?.maxLength;
  return typeof max === 'number' ? max : undefined;
}

/**
 * Find the image URL field name (start_image_url or image_url).
 *
 * Exported as {@link hasStartFrameField} so callers can ask whether an
 * endpoint takes a real start frame without duplicating the answer into a
 * config that could then disagree with the schema.
 */
function getImageUrlField(schema: MotionJSONSchema): string | undefined {
  const props = schema.properties;
  if ('start_image_url' in props) return 'start_image_url';
  if ('image_url' in props) return 'image_url';
  return undefined;
}

/**
 * Does this endpoint accept a still in a dedicated start-frame field?
 *
 * True for every image-to-video schema, and — among the reference-to-video
 * endpoints — only for Kling O3, whose `start_image_url` is optional. The
 * transform maps our `imageUrl` onto whichever field this finds, so passing
 * it to an endpoint without one is a no-op rather than a bad request.
 */
export function hasStartFrameField(schema: MotionJSONSchema): boolean {
  return getImageUrlField(schema) !== undefined;
}

// ---------------------------------------------------------------------------
// Transform helpers
// ---------------------------------------------------------------------------

const zMotionInput = z.looseObject({
  prompt: z.string(),
  duration: z.number().optional(),
  imageUrl: z.string().optional(),
  aspectRatio: z.string().optional(),
});

export function numericOf(v: string | number): number {
  return typeof v === 'number' ? v : parseFloat(v);
}

export function snapTo(
  n: number,
  values: readonly (string | number)[]
): string | number {
  const numeric = values.filter((v) => !Number.isNaN(numericOf(v)));
  return numeric.reduce((prev, curr) =>
    Math.abs(numericOf(curr) - n) < Math.abs(numericOf(prev) - n) ? curr : prev
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Create a Zod transform from an API schema + its JSON Schema metadata.
 *
 * Accepts camelCase input (prompt, duration, imageUrl, aspectRatio),
 * transforms to the API's snake_case format, and validates.
 */
export function motionTransform<T extends z.ZodObject<z.ZodRawShape>>(
  apiSchema: T,
  jsonSchema: MotionJSONSchema
) {
  const durationValues = getDurationValues(jsonSchema);
  const imageUrlField = getImageUrlField(jsonSchema);
  const maxPromptLength = getPromptMaxLength(jsonSchema);

  return zMotionInput.transform((input): z.infer<T> => {
    const { imageUrl, aspectRatio, duration, prompt, ...rest } = input;
    // A `maxLength` in fal's own schema is a ceiling fal enforces, so this is
    // the one place a prompt is refused rather than sent (#1754). It used to
    // be cut down to fit, which shipped a prompt nobody had seen; now the
    // motion rescue shortens it into a visible prompt version instead.
    assertPromptWithinHardLimit(prompt, maxPromptLength);
    const raw = {
      ...rest,
      prompt,
      ...(imageUrl && imageUrlField && { [imageUrlField]: imageUrl }),
      ...(aspectRatio && { aspect_ratio: aspectRatio }),
      ...(duration !== undefined &&
        durationValues.length > 0 && {
          duration: snapTo(duration, durationValues),
        }),
    };
    return apiSchema.parse(raw);
  });
}
