/**
 * Upload rights (#1581) — the client-safe half.
 *
 * Every image a user brings in is checked for a real person before anything
 * uses it, and a real person needs the uploader's portrait sign-off. The
 * ledger row is keyed by the SHA-256 of the stored URL, so one still is
 * checked once per team no matter where it is used next.
 */

import { PORTRAIT_RIGHTS_V1 } from '@/platform/compliance/attestations';
import { getPublicAssetsDomain } from '@/platform/public-assets';
import { mediaUrlSchema } from '@/platform/schemas/media-url.schemas';
import { z } from 'zod';

/** What the ledger says about one upload. `null` on the wire means unchecked. */
export type UploadRights =
  /** The check found no real person; nothing is asked of the user. */
  | { status: 'cleared' }
  /** A real person, and the portrait sign-off is on record. */
  | { status: 'signed' }
  /** A real person, and the sign-off is still owed. */
  | { status: 'needs_portrait' };

/** One image to check: the stored URL, plus the original filename as a hint. */
export const uploadRefSchema = z.object({
  url: mediaUrlSchema,
  filename: z.string().max(255).optional(),
});
export type UploadRef = z.infer<typeof uploadRefSchema>;

/** The portrait sign-off for one upload. The only statement a user signs. */
export const portraitAttestationSchema = z.object({
  url: mediaUrlSchema,
  statementVersion: z.literal(PORTRAIT_RIGHTS_V1.version),
  authorizationBasis: z.string().trim().min(1).max(500),
});
export type PortraitAttestation = z.infer<typeof portraitAttestationSchema>;

/**
 * Whether a URL used at generate time still needs a rights check (the
 * studio composer, and anything else that takes a URL rather than a row).
 *
 * Gated: a raw http(s) URL, and anything under a folder a signed upload can
 * write to and nothing gates on the way out — `temp/` (talent and location
 * uploads not yet saved to a library row) and elements' `uploads/`. Exempt:
 * every other stored `/r2/` object, which is either generated by us or was
 * written through a library flow that ran this same check, and our own
 * public assets domain (system talent, locations and styles ship from
 * there).
 */
export function needsLikenessCheck(url: string): boolean {
  if (url.startsWith(`https://${getPublicAssetsDomain()}/`)) return false;
  return (
    /^https?:\/\//.test(url) ||
    /^\/r2\/(talent|locations)\/[^/]+\/temp\//.test(url) ||
    /^\/r2\/elements\/[^/]+\/uploads\//.test(url)
  );
}
