// AUTO-GENERATED by scripts/generate-style-briefs.ts --variants — do not edit by hand.
// Alternative sample briefs per style, on top of the canonical one in
// style-briefs.generated.ts. The composer picks between all of them (#1393).

/**
 * Consumed by `sampleScriptsForStyle` in `composer-sample.ts`.
 * @public
 */
export const STYLE_BRIEF_VARIANTS: Record<string, string[]> = {
  'product-ad': [
    'A woman with wet dark hair and a white robe presses a pump of amber face serum into her palm at a sunlit bathroom sink, fingers smoothing it over her cheek as a macro cut catches the glossy droplet sliding down the glass bottle.',
    'A man with cropped curls and a linen shirt tears the kraft tab off a coffee bean pouch on a bright kitchen counter, beans tumbling into a grinder as an overhead flat-lay reveals the bag, brass scoop, and one orange ceramic cup.',
  ],
  'real-estate': [
    'A woman with a sleek dark chignon in a cream silk robe pushes open the floor-to-ceiling glass doors of a marble penthouse living room, walking out onto the terrace as the camera dollies after her through long amber beams of late-afternoon sun.',
    'A blonde woman in an emerald satin evening dress pours red wine at a backlit travertine kitchen island, then carries the glass past a glowing pendant fixture toward the sunset-filled dining room as the camera glides through the doorway behind her.',
  ],
  animatic: [
    'A rough pencil-and-marker pre-vis frame of a lanky male courier in a hooded jacket skidding his bicycle around a rain-slicked corner, satchel swinging wide as loose parcels tumble loose across the paper-toned street, the camera pushing gently in on his gritted-teeth reaction.',
    "A sketched wide of a woman with a long braid and heavy overcoat hauling open a rusted barn door with both hands, hay dust flicking up in a few decisive strokes as a startled horse rears in the grey-washed dark behind her, camera slowly panning to follow the door's swing.",
  ],
  corporate: [
    'A woman with a sleek dark ponytail in a light grey blazer stands at a glass whiteboard in a sunlit open-plan office, uncapping a marker and sketching a product roadmap as the gimbal glides past her toward two colleagues nodding at the diagram.',
    'Over-the-shoulder, a bearded man in a navy button-down scrolls a SaaS analytics dashboard on a wide monitor, clicking through to a live chart that animates upward, then turns to camera in a slow push-in to explain the spike.',
  ],
  'award-season': [
    "In a dim kitchen lit by one low window, a grey-haired man in a frayed cardigan sets two plates on the table, then slowly removes the second one as he realizes he's alone, the camera pushing in on his trembling hands.",
    "A young woman with dark braids and a rain-soaked denim jacket steps into her late mother's cluttered sewing room, pulls a dust sheet off the machine in a slow drift of light-caught dust, and sits down to thread a needle as tears rise.",
  ],
  documentary: [
    'A weathered fisherman in a yellow oilskin jacket and grey stubble hauls a dripping net over the gunwale of a small trawler at dawn, silver fish thrashing across the wet deck as the handheld camera ducks and steadies against the swell in flat natural light.',
    'In a cramped tin-roofed workshop, a woman with grey braided hair and a paint-flecked apron spins a clay pot on a kicking wheel, wet hands rising to shape the rim while dust drifts through a shaft of window light and the camera drifts around her shoulder.',
  ],
  action: [
    'A stubble-jawed male stunt rider in a scuffed black leather jacket guns a dirt bike up a collapsing desert canyon ramp, sand and sparks exploding behind him as a sweeping crane shot whips overhead into the teal dusk sky.',
    'A woman with a tight braid and torn orange flight suit sprints along the wing of a taxiing cargo plane, wind tearing at her as she leaps for a dangling cargo strap while the runway lights streak past in saturated blur.',
  ],
  'rom-com': [
    'In a sun-drenched corner bakery, a curly-haired woman in a mustard cardigan reaches for the last cinnamon roll at the same moment a lanky man in a rumpled denim shirt does, their hands collide, the tray tips, and they both burst into laughter as powdered sugar clouds the warm golden air.',
    'On a rain-slicked city street glowing with warm shopfront light, a man in a soggy grey blazer sprints after a runaway yellow umbrella, catches it, and turns to find a woman with a short black bob in a red trench coat already sharing his taxi, both grinning as they climb in.',
  ],
  animated: [
    "In a rain-drowned neon alley, a young woman with cropped silver hair and a patched oxblood trench coat sprints across flooded pavement, vaults a stack of crates, and skids to a stop as a hovering drone's searchlight sweeps down through the haze, her face lit hard by pink signage.",
    "Inside a collapsing cathedral-observatory, an older man with a grey beard and soot-streaked scholar's robes cranks a vast brass orrery, god rays pouring through the shattered dome as gears grind, dust spirals upward, and the planetary rings swing open to reveal a glowing bioluminescent map.",
  ],
  'neo-noir-thriller': [
    'A gray-haired male detective in a rumpled trench coat slams a manila file onto his desk, venetian blind shadows striping his face as he yanks the cord to peer down at a rain-slicked neon street where a black sedan pulls away.',
    "A young woman with a sleek black bob and a red satin dress hurries through a flooded parking garage, heels splashing under flickering sodium lights, then spins as a car's headlights snap on behind her and a shadowed figure steps out.",
  ],
  pastel: [
    'In a powder-blue hotel lobby, a mustachioed bellhop in a mint uniform wheels a brass cart stacked with leather suitcases dead-center toward the camera, halts, rings the desk bell twice, and a lavender-suited woman with a blonde bob slides a room key across the counter.',
    'Inside a butter-yellow laundromat, a woman with a blunt auburn bob and a dusty-pink cardigan yanks open a dryer door, releasing an avalanche of mismatched socks onto the checkered floor; she kneels, folds one pair with deadpan precision, and stares straight into the lens.',
  ],
  'sci-fi-futuristic': [
    'A male engineer with a shaved head and a fitted charcoal exosuit strides along a curved white corridor of an orbital station, swiping a teal holographic schematic apart with both hands as cool LED strips pulse and the camera glides wide to reveal Earth turning beyond the glass.',
    'A woman with a silver-streaked braid and a sleek navy flight jacket drops into the cockpit of a docked shuttle, tapping glowing blue holo-controls that bloom around her as the canopy seals, lens flares sweeping across the glass while the craft lifts from its teal-lit landing cradle.',
  ],
  'horror-gothic': [
    'A pale young woman in a high-collared black mourning dress lifts a guttering candelabra and climbs the warped spiral staircase of a derelict cathedral tower, her skirts dragging as the flame gutters and a tall shadow slides down the stone wall behind her.',
    'A gaunt bearded gravedigger in a soaked oilskin coat heaves his spade into wet earth beside a leaning angel headstone, then freezes as the iron cemetery gate swings open by itself and mist pours between the crypts toward him.',
  ],
  'western-epic': [
    'A weathered male cowboy in a dust-caked duster and wide-brimmed hat rides his chestnut mare along a mesa ridge at magic hour, spurring into a canter as long shadows stretch across the valley and a slow wide zoom pulls back over the sunlit badlands.',
    'A young woman with a long dark braid and a canvas work coat hauls a stubborn oxen team and loaded wagon across a shallow river crossing at sunset, water spraying and wheels churning mud as the wide frame holds the golden dust cloud behind her.',
  ],
  'lo-fi-retro': [
    'A young man in a red hoodie with messy black hair films himself walking a golden retriever through a suburban park at golden hour, the phone jittering as the dog lunges after a tennis ball and the blown-out sky clips white behind swaying trees.',
    "A woman with a blonde ponytail in a denim jacket blows out candles on a grocery-store birthday cake in a dim apartment kitchen, friends' hands clapping into frame as the phone swings toward the crushed, noisy shadows and glowing overhead lamp.",
  ],
  'glossy-product-hero': [
    'A brushed-titanium mechanical watch rises on a mirrored black turntable, rotating slowly as a rim light sweeps its sapphire crystal, then a hyper-smooth dolly-in pushes to macro as the second hand ticks and the crown catches a crisp specular flare.',
    'A frosted-glass perfume bottle descends onto a sculpted charcoal gradient plinth, its faceted cap settling with a glint, then the camera glides in as a single amber droplet slides down the shoulder of the bottle and the gold brand mark ignites under a hero kicker.',
  ],
  'premium-lifestyle': [
    'A woman with loose dark waves in a cream linen robe steps onto a sunlit Mediterranean balcony, pours iced tea from a frosted glass carafe as late-day light rakes across marble, then lifts the glass to her lips while the camera racks from her hand to her smile.',
    'A man with close-cropped black hair and an unbuttoned oatmeal shirt grinds coffee beans in a bright marble kitchen, tilts the steaming pour-over into a stoneware cup, and carries it to a linen sofa where morning window light catches the rising steam as he settles back.',
  ],
  'beach-ritual': [
    'A woman with long wet dark hair in a coral one-piece swimsuit wades out of the turquoise surf, pushes her hair back and shakes droplets off her shoulders, then drops onto a striped towel on hot sand and smooths sunscreen along her golden forearm as the low sun flares across the lens.',
    "A man with sun-bleached curls in open linen shirt and swim shorts strides down a weathered timber jetty, pops the tab on a frosted can of citrus seltzer, and lifts it against the sparkling horizon while sea breeze snaps his shirt and a friend's splash bursts below him.",
  ],
  'beauty-macro': [
    "A glass dropper hovers above a woman's cheek and releases a single amber serum bead that lands and slowly spreads across dewy, pore-detailed skin, as the macro lens pushes in on her fingertip smoothing it in a glowing peach-lit sweep.",
    "A frosted lipstick bullet twists up from its gold case and glides slowly across a woman's parted lips in extreme macro, leaving a rich rose stripe, then the camera rotates as she presses her lips together and a soft edge light blooms along the pigment.",
  ],
  'automotive-cinematic': [
    'A matte-black electric sedan carves through a hairpin on a misty mountain pass at low golden sun, drone sweeping ahead as the car powers out of the corner, then a low tracking pass skates hard light across its rear haunch and spinning wheel.',
    'On cracked white salt flats at blue hour, a deep-red sports coupe launches from stillness, throwing a plume of dust as a long-lens chase car compresses it against a violet sky, before a slow rotational beauty pass circles the parked hero, headlights igniting.',
  ],
  'fashion-editorial': [
    "In a bare concrete hall cut by one hard shaft of window light, a tall woman with a slicked-back black bun and an oversized scarlet wool coat strides three deliberate steps into frame, stops, and turns her head slowly as the coat's hem swings and settles.",
    'On wind-raked ochre dunes at low sun, a man with close-cropped hair and a billowing ivory linen suit lifts one arm so the fabric snaps sideways, then walks the ridge line as the locked wide frame slowly dollies in on his silhouette.',
  ],
  'luxury-still': [
    "A single amber-filled cut-crystal decanter sits on a walnut slab beside one bruised plum as a slow pour sends whisky spiraling into a heavy tumbler, ice cracking and light refracting, the camera creeping in for a macro pass across the glass's beveled facets in deep chiaroscuro.",
    "On a raw limestone plinth, a hand-thrown matte-black ceramic vessel turns under a slow orbital track while a man's weathered hands in rolled linen sleeves lower a single dried magnolia branch into it, dust motes drifting through the side window light as shadow swallows the far edge.",
  ],
  'food-beverage-hero': [
    "A chef's hands lift a bubbling cast-iron skillet, backlit steam curling as butter slides over a seared ribeye on aged wood, then a slow macro pull follows the spoon dragging garlic-herb sauce across warm marble.",
    'Golden syrup ribbons in slow motion over a stack of buttermilk pancakes on raw linen, a knob of butter melting into glossy pools, then a probe lens dives past cracking ice as cold brew tumbles into a frosted glass.',
  ],
  'tech-keynote': [
    'A matte-black smart ring rises on an invisible pedestal into a dark seamless stage frame, rotating a slow full turn as twin blue gradient orbs bloom behind it and translucent heart-rate UI panels slide into clean perspective around its brushed edge while the camera dollies in on rails.',
    'A presenter — a woman with a sleek dark bob and a charcoal turtleneck — strides to center stage, turns to camera and talks through the launch, sweeping one hand as a giant glowing chip diagram assembles layer by layer beside her, the locked frame easing into a measured dolly-in.',
  ],
  'fintech-explainer': [
    'A woman with curly dark hair in a cream sweater sits cross-legged on her sunlit apartment sofa, taps her phone to split a shared rent payment, then exhales and smiles as the flat-on UI insert pushes into a glass card animating the split into three settled avatars.',
    'A bearded man in a linen shirt stands at his kitchen island, sliding a finger across his tablet to nudge a savings goal higher while the kettle steams beside him, then the camera cuts to a measured push-in as the soft dashboard ring fills toward its target.',
  ],
  'perfume-editorial': [
    'In a bare walnut-toned room, a woman with long dark waves and a bronze silk slip dress steps through a billowing sheer curtain as hard sunlight cuts the haze, her hand grazing her collarbone before the camera glides down to a faceted amber bottle on a stone ledge, rim light igniting the glass.',
    "Dust swirls in a single window shaft as a man with cropped black hair and an open ivory linen shirt lifts a crystal flacon and mists the air in slow motion, the camera rotating around the droplet cloud before pushing macro into liquid trembling against the bottle's edge.",
  ],
  'watch-macro': [
    'A brushed-steel dive watch rotates slowly on a black glass turntable against a deep charcoal gradient, its ceramic bezel clicking one notch as a strip light sweeps the polished lugs, then a probe-lens macro push isolates the sweeping second hand ticking across sunburst-blue lacquer.',
    'A rose-gold skeleton chronograph lies dial-down under macro light as the golden rotor swings and the balance wheel oscillates through a sapphire caseback, then the watch tilts upright on an unseen rig, crown screwing shut as a kicker ignites each applied index.',
  ],
  'sportswear-motion': [
    'A male sprinter with close-cropped hair in a black singlet and neon-accented spikes explodes from the blocks in an empty floodlit stadium, tracking camera racing alongside as sweat beads fly and his foot slams the wet track in 240fps slow motion.',
    'In a neon-lit night gym, a woman with a high braided ponytail in a teal crop top and leggings chalks her hands, then swings up onto the pull-up bar, chalk dust bursting through the rim light as she drops and exhales, chest heaving.',
  ],
  'alcohol-pour': [
    "A single large ice sphere drops into a heavy crystal tumbler on dark slate, then amber single-malt whisky arcs from the tilting bottle in slow motion, splashing gold against the glass wall as the backlit label glows and condensation beads slide down the bottle's shoulder.",
    'A frosted craft lager bottle uncaps with a burst of vapor on a seamless charcoal backdrop, then straw-gold beer cascades into a tilted pilsner glass, foam climbing and cresting the rim while the camera tracks slowly around the rim-lit bottle silhouette.',
  ],
  'jewellery-rotation': [
    "A solitaire diamond engagement ring stands on a black velvet cone and rotates with glacial precision, pinpoint lights sweeping across its facets to throw fire, before a macro probe glides into the platinum setting and a woman's hand with short nude nails lifts it away.",
    "A heavy gold statement necklace with emerald cabochons lies coiled on a pale stone slab, turning slowly on a hidden turntable as backlight ignites the green stones, then a woman's hand slides beneath the chain and lifts it so the links unfurl and swing in slow motion.",
  ],
  'hospitality-lifestyle': [
    'A woman with long dark hair in a white linen shirt-dress pushes open tall shutters onto a cliffside terrace, walks barefoot to the infinity pool edge as the camera glides behind her, and lowers herself in as morning sun scatters across the water toward the horizon.',
    'A man with cropped grey hair in a pale unbuttoned linen shirt pours coffee at a shaded breakfast table on a sea-view balcony, a server sets down a bowl of figs and pastries on the crisp linen, and the gimbal drifts past them out over the palms and bay.',
  ],
  'white-background-studio': [
    'A matte-black cordless stick vacuum stands centered on pure white seamless, slowly rotating through its front three-quarter and profile angles as the transparent dust canister clicks free and lifts away, then a macro pass glides across the brushed-metal wand and power trigger detailing.',
    'A tan full-grain leather weekender bag sits centered on white seamless as its brass zipper glides open to reveal the lined interior, the bag turning slowly on a hidden platform before a locked macro frame tracks along the hand-stitched handle seam and embossed logo plate.',
  ],
  'lifestyle-on-model': [
    'A woman with dark curly hair in a cream linen shirt sits on a sunlit kitchen counter, unscrews a glass moisturizer jar, dots the cream along her cheekbones and smooths it in, then smiles as she twists the lid closed and sets the jar down beside a bowl of lemons.',
    'A man with a short beard in a rust-orange puffer jacket shoulders a canvas backpack on a leafy morning sidewalk, tugs the strap snug, unzips the front pocket to pull out a steel water bottle, drinks, and walks on as dappled daylight moves across him.',
  ],
  'ugc-unboxing': [
    "A woman's hands with chipped mint nail polish slice packing tape off a small kraft box on a sunlit coffee table, peel back crinkling tissue, and lift a matte green ceramic espresso cup into frame beside a laptop and trailing pothos, turning it slowly for the camera.",
    "Man's hands with a beaded bracelet tear open a padded mailer on a cluttered desk, shake out a pair of white wireless earbuds, pop the charging case lid open and shut twice, then hold one bud toward the lens as a mug of coffee steams behind it.",
  ],
  'flat-lay-overhead': [
    "Directly overhead on raw oak, a woman's hands with a linen sleeve set a matte ceramic pour-over mug beside a leather notebook, then twist the mug handle straight and lay a rosemary sprig into the negative space as the camera pushes slowly in.",
    "Locked top-down on cool marble, a man's hand in a rolled chambray sleeve arranges a steel dive watch, folded navy linen and a sliced grapefruit into a tight arc, sliding the watch a few millimeters as the frame rotates gently around it.",
  ],
  '360-turntable': [
    'A matte-black cordless espresso machine sits centered on a seamless pale-grey gradient backdrop and rotates a full slow 360 degrees on a motorized turntable, softbox light gliding across its brushed steel drip tray, chrome portafilter handle and illuminated blue power ring as each angle passes the locked camera.',
    'A pair of white-and-mint running shoes, laces tied and set heel-to-toe on a seamless warm-grey gradient sweep, turns steadily through a complete 360 on the turntable, the rim light raking over mesh uppers, stitched logo and lugged outsole tread as the profile, rear and toe views rotate into frame.',
  ],
  'as-seen-on-phone': [
    "A woman with dark curly hair in an oatmeal knit sweater holds her phone above a sunlit kitchen counter, her thumb flicking past two clips until a vertical ad for a matte-black insulated water bottle fills the screen — condensation beading as it's poured — and the camera pushes to macro on the bezel as she taps the product page open.",
    'A man with a cropped beard in a grey tee sits on a linen sofa, tilting his phone as he scrolls a feed; a chunky white sneaker spins into frame on screen, he pinches to zoom on the stitched heel tab, then thumbs the Add to Cart button while the screen glow flickers across his fingers.',
  ],
  'marketplace-listing': [
    'A stainless steel insulated water bottle rotates slowly on an invisible turntable against pure white, its brushed body catching even softbox light, then its bamboo lid twists off and lifts away to reveal the threaded mouth in a locked square hero frame.',
    'A pair of white leather sneakers sits centered on blown-out white, tipping smoothly onto its side to expose the treaded outsole, then rotating a quarter turn as one lace end unfurls and settles, filling the frame in flat, shadow-controlled clarity.',
  ],
  'kitchen-counter-ugc': [
    'A woman with a messy brown bun and an oversized grey sweatshirt twists open a tub of vanilla protein powder on a cluttered kitchen counter, scoops a heaping measure into a blender jar of banana and oat milk, snaps the lid on and blends as the handheld phone camera jitters in and refocuses on the swirling drink.',
    'A man with cropped black hair and a rolled-sleeve flannel tears a lemon electrolyte stick pack over a tall glass of ice by the sunlit kitchen window, pours water from a filter jug so the powder fizzes and clouds, then stirs with a spoon and lifts the glass toward the shaky phone lens.',
  ],
  'returns-friendly-diagnostic': [
    "A man's hands with short-trimmed nails set a slate-grey canvas weekender duffel on a white studio table, lay a metal tape measure across its 22-inch length, unzip the main compartment to show the padded laptop sleeve, then hold a phone against the side pocket for scale as the bag slowly rotates.",
    "A woman with dark curly hair in a ribbed oatmeal knit midi dress turns slowly on a seamless white studio cyc so the drape and side slit read clearly, smooths the fabric over her hip, then holds a stretched cuff toward the macro lens where the knit's weave and weight fill the frame.",
  ],
  'packaging-close-up': [
    "A matte-black coffee bag rotates slowly on a turntable as raking light crawls across its embossed mountain logo, then a woman's hand with copper-ringed fingers peels back the gold foil seal, tiny bean fragments tumbling past the macro probe lens.",
    "A cream letterpress perfume box slides open on a turntable, its deep-debossed serif lettering catching raking light, then a man's hand in a charcoal cuff tugs a silk ribbon that unspools and slips off the lid, tissue paper crackling open.",
  ],
  'in-context-use': [
    'A man with a short dark beard in a grey flannel shirt clips a compact insulated cooler onto his bike rack at a sunlit park picnic table, unzips the lid, and lifts out two still-frosted bottles as condensation runs down the glass, tight insert catching the zip pull and the crisp cap twist.',
    'A woman with a curly auburn ponytail in an oversized cardigan drops into her desk chair at dusk, taps the base of a slim folding LED lamp so warm light floods her cluttered sketchbook, then angles the arm lower and resumes shading, the pencil line sharpening under the beam.',
  ],
  'warm-vlog': [
    'A woman with curly dark hair in an oversized cream cardigan curls onto her sofa, cradling a steaming mug as she leans toward the camera mid-story about her move across the country, gesturing with one hand while her terrier hops up beside her and fairy lights glow behind.',
    'A man with a short beard in a rumpled flannel shirt talks to camera from his kitchen island, pouring water over coffee grounds and stirring as he explains why he quit his agency job, glancing up between pours while afternoon window light rakes across plants and stacked books.',
  ],
  'ring-light-tutorial': [
    'A woman with tight box braids in a mustard turtleneck leans toward camera at her vanity explaining a two-minute cream-blush routine, gesturing with the stick, then an overhead insert shows her fingers tapping and blending the color across her cheek.',
    'A man with a close-cropped beard in a charcoal henley sits at a tidy desk beside a trailing pothos, talking through how to clean a mechanical keyboard, popping a keycap free mid-sentence before an overhead cut shows his hands brushing dust from the switches.',
  ],
  'podcast-clip': [
    'A bearded male host in a charcoal knit sweater leans into his boom mic to argue that no one should quit their job for a startup, while his female co-host with box braids and an olive blazer laughs, shakes her head and cuts in, both gesturing across the wood-top table as the lens slowly punches in.',
    'A red-haired female host in a cream turtleneck slides a printed chart across the wood table toward her guest, a young man in a plaid shirt and glasses, who picks it up, taps it and answers into his broadcast mic, both swiveling toward each other under the warm neon-lit shelving.',
  ],
  'street-interview': [
    'On a sun-blasted downtown sidewalk, a man in his thirties with a shaved head and a denim jacket laughs and gestures wide as he answers an off-camera question about his morning commute, leaning toward the handheld mic while buses and pedestrians sweep past behind him.',
    'At a crowded outdoor farmers market on an overcast afternoon, a woman with curly auburn hair and a mustard cardigan holds up a bag of peaches while explaining her weekly shopping ritual to an off-camera interviewer, stepping aside mid-sentence as a vendor wheels a crate past her.',
  ],
  'bedroom-confessional': [
    'A young woman with messy dark curls in an oversized grey sweatshirt sits cross-legged against her headboard, hugging a pillow as she tells the camera about quitting her job, wiping her eyes and laughing shakily while the bedside lamp glows behind her.',
    'A bearded man in a faded flannel pajama shirt sits on his bedroom floor beside an unmade bed, turning a folded letter over in his hands as he quietly explains to the camera why he finally called his father, window light fading across his face.',
  ],
  'kitchen-tutorial': [
    'A woman with dark curly hair in a mustard apron leans into the counter camera explaining her one-pan lemon chicken, then the overhead cuts to her hands sliding golden thighs into a sizzling skillet and scattering torn herbs over the crackling skin.',
    'A bearded man in a rolled-sleeve denim shirt talks to camera while flouring his board, then the top-down camera catches him kneading and folding a pillowy focaccia dough, dimpling it with his fingertips as olive oil pools and glistens in the wells.',
  ],
  'gym-selfie-cam': [
    'A muscular man in a black tank top and backwards cap holds his phone at the squat rack mirror, racking the loaded bar with a clang, then wipes sweat from his buzzed hair and talks straight into the mirror selfie between heaving breaths as other lifters move behind him.',
    'A woman with a high ponytail in teal leggings and a cropped hoodie chalks her hands, rips a slow-motion deadlift off the rubber floor with plates rattling, then drops to a knee in front of the phone propped on a bench and breathlessly counts off her set to camera.',
  ],
  'car-talk': [
    'A woman with curly dark hair in an olive utility jacket drives through late-afternoon city traffic, seatbelt across her chest, glancing between the dash-mounted camera and the road as she animatedly recounts quitting her corporate job, hands tapping the wheel while sun-and-shadow stripes sweep across her face.',
    'A bearded man in a grey hoodie and cap steers along a coastal highway at golden hour, laughing into the windscreen-mounted camera while breaking down his worst business mistake, gesturing off the wheel, checking his mirror, then turning to a passenger-seat profile as palm trees flick past his window.',
  ],
  'walking-and-talking': [
    'A man in his thirties with cropped black curls, olive jacket and white tee strides down a bustling market street, gesturing as he talks straight to the gimbal about his morning coffee ritual, then turns to point at a steaming espresso cart as vendors and shoppers slide past behind him.',
    'A woman with a high blonde ponytail, denim jacket and running shoes power-walks a riverside park path, laughing to camera as she explains her new training plan, then steps aside to let cyclists pass and gestures up at the skyline glowing in late-afternoon backlight.',
  ],
  'reaction-cam': [
    "A young man with messy curls and an oversized black hoodie leans into his desk mic, eyes widening then hands flying to his head as the inset clip shows a skateboarder's impossible rail slide, purple LED panel glowing behind his gaming chair.",
    'A woman with slicked-back blonde hair and gold hoops squints at a teal-lit monitor, then jerks back laughing and slaps the desk as the corner inset plays a wildly overhyped gadget infomercial, posters and pink LED strip blazing behind her.',
  ],
  'bedtime-storybook': [
    'A small round hedgehog in a knitted blue scarf pads across a moonlit meadow carrying a paper lantern, pausing to nudge a sleepy firefly awake as the tall painted grasses sway and the camera drifts slowly through layered twilight hills.',
    'A curly-haired girl in a star-patterned nightgown climbs onto her windowsill and reaches out to a passing cloud-whale, which dips low, gathers her onto its back, and glides over the painted rooftops of a sleeping village while lit windows blink goodnight.',
  ],
  'saturday-morning-cartoon': [
    'A goofy orange tabby cat in a backwards green cap pedals a rickety soapbox racer down a candy-colored hill, wheels smearing into blur lines, then crashes into a haystack and pops out grinning with straw in his whiskers as the camera shakes on impact.',
    'A pigtailed girl in red overalls yanks the lever on a bubblegum-pink invention machine in her cluttered treehouse lab, springs boing, gears spin, and a giant soap bubble balloons out and lifts her squealing off the floorboards as her tiny blue robot sidekick grabs her shoe.',
  ],
  claymation: [
    'A stubby clay bear in a red knitted scarf wobbles across a cardboard kitchen diorama, hoists a lopsided honey jar onto a clay table, pries the lid off with both paws, and gets splattered with a slow golden ribbon of clay honey as thumbprints catch the warm tungsten key light.',
    'A clay boy with a mop of orange hair and blue overalls cranks a handmade cardboard rocket on a tabletop launchpad, ducks as clay smoke puffs bloom frame by frame, and the wobbling rocket lifts past painted cardboard clouds while he waves and jumps in quirky stop-motion beats.',
  ],
  'paper-cutout': [
    'A scissored-card paper fox with brad-jointed legs trots along a folded green paper hillside, hops a sky-blue river cut from card, and startles a flock of layered paper birds that flutter up in jerky stop-motion as the background hills slide past beneath the locked top-down key light.',
    'A cutout paper girl with orange yarn-paper hair and a red card dress waters a construction-paper seed, and a layered green stem unfolds petal by petal into a giant vivid paper sunflower, its clean drop shadow stretching across the craft-table background.',
  ],
  'watercolour-fable': [
    'A small painted hedgehog in a red knitted scarf pushes a fallen acorn up a dew-soaked hillside at dawn, slipping once as the acorn rolls back, while soft washes of meadow grass bleed at the edges and the camera drifts slowly alongside him.',
    'A young girl with long dark braids and a yellow raincoat wades into a twilight pond to free a paper boat tangled in reeds, ripples spreading in loose brush strokes as a heron lifts off, wings rendered in two decisive grey strokes above her.',
  ],
  'pop-up-book': [
    'A hinged paper spread unfolds to raise a cut-paper pirate ship that rocks on scissored blue wave layers while a boy captain in a folded red coat and paper tricorn cranks a tab, tilting the mast as a paper whale spouts confetti spray behind him.',
    'Paper flaps swing open to build a layered jungle where a cut-paper elephant swings its hinged trunk, palm fronds slide apart on staggered planes, and a girl explorer in a khaki vest with paper braids climbs a folding rope bridge as toucans pop up in sequence.',
  ],
  'felt-and-yarn': [
    'A stitched-felt hedgehog boy in a mustard yarn scarf and button eyes wobbles across a knitted green hillside, tugging a wooden thread-spool cart that tips over and spills woolly felt apples that roll and bounce down the fabric slope while he scrambles after them.',
    'A grandmotherly felt mouse puppet in a patchwork apron and grey yarn bun stands at a fabric kitchen table, stitched paws kneading a lump of cream felt dough, rolling it flat and pressing out little star cookies as a hand-sewn oven door creaks open behind her, releasing a curl of cotton-wool steam.',
  ],
  'chalkboard-doodle': [
    'On a dark green slate, white chalk strokes race outward to draw a seed, then a sprout that climbs and unfurls pastel leaves as an unseen hand smudges away the soil line and chalk-dust rain falls, the camera pushing in as a yellow chalk sun spins to life above.',
    'Chalk lines snap together into a rickety rocket on near-black slate, a stick-figure astronaut doodle waves from the hatch, then countdown numbers are drawn and erased one by one before a burst of pastel chalk-dust exhaust lifts the rocket up past hand-drawn planets as the frame tilts to follow.',
  ],
  'lo-fi-anime': [
    'A teenage boy with messy black hair and an oversized navy school cardigan rides an empty commuter train at magic hour, forehead against the glass as painted rice fields slide past in parallax, then he lifts his hand to trace the fogged window while the carriage sways and his headphone cord swings.',
    "A teenage girl with a short brown bob and a yellow raincoat pushes open the glass door of a corner store, shakes rain from her sleeves, and slowly spins the squeaking magazine rack while the shopkeeper's fan turns overhead and warm afternoon light breaks through the clouds outside.",
  ],
  'hand-drawn-picture-book': [
    'A round-faced boy with messy orange hair and red rubber boots stomps through crayon-scribbled puddles on a cream paper street, splashing bright blue drops as a striped umbrella tumbles away and a grinning yellow dog bounds after it.',
    'A small girl with two black braids and a green dress tugs a wobbly wagon of crayon-drawn sunflowers up a hill, then lets go so the wagon rolls back down while parallax clouds and a fat orange cat drift past behind her.',
  ],
  'rough-storyboard': [
    'A rough pencil-and-marker storyboard frame: a bearded man in a long coat hauls open the rusted hatch of a stranded freight train, marker-wash steam bursting up around his silhouette as he ducks and climbs down into the dark, gestural hatching sliding across the warm paper.',
    'A rough pencil-and-marker storyboard frame: a woman with a short bob and a leather jacket kicks her motorcycle to life in a rainy alley, wheel spinning up a smear of marker-bleed spray as she leans hard and rides out toward the lit street beyond.',
  ],
  'low-detail-blockout': [
    'A grey low-poly mannequin in a boxy trench-coat silhouette strides across a greybox subway platform as a simple box-geometry train slides into frame behind him, the wide layout camera tracking slowly left to verify the crossing action.',
    'Two featureless grey mannequins — one with a blocky ponytail primitive, one in a simple box hard-hat — walk a greybox construction-site gangway, gesturing toward a rising box-crane arm as the single wide camera dollies in slowly to check the staging.',
  ],
  'mood-only-frames': [
    'A man in a long charcoal overcoat, dark hair slicked by rain, steps slowly through amber sodium-lit fog toward a flooded alley puddle, his silhouette swelling in the frame as the locked camera pushes in and neon reflections ripple beneath his boots.',
    'A woman with loose auburn curls in a white slip presses her palm to a fogged window, dragging it downward through condensation as hard teal dawn light floods the gap, dust swirling in the beam while the static frame slowly creeps closer to her hand.',
  ],
  'black-white-previz': [
    'A monochrome staging pass follows a woman with a short bob and a pale trench coat as she pushes through a warehouse door, hard key light slicing shadow bars across her face while the dolly glides in, and she halts mid-step to look up at a swinging overhead lamp.',
    'In a black-and-white previz, a young man in a rumpled shirt sprints up a concrete stairwell, rim light carving his silhouette against volumetric haze as the crane rises with him, and he bursts onto the rooftop where a single red beacon pulses in the distance.',
  ],
  'schematic-concept': [
    'An isometric schematic of a cordless espresso machine sits on pale paper-grain background as its housing separates into exploded layers—pump, brass boiler, water tank—each floating apart while dashed callout boxes snap open and leader-line labels type themselves, then the camera slowly zooms into the highlighted teal boiler coil.',
    'A cutaway isometric diagram of a rooftop rainwater-harvesting system draws itself line by line across a gridded technical sheet, animated dashed arrows tracing water down gutters into a filter drum and cistern, then the frame pushes in on the pump module as its callout box expands and labels fan out on leader lines.',
  ],
  'marker-rough': [
    'A marker-comp animatic of an ad concept: a man in a red windbreaker with cropped black hair sprints down a warm-paper street toward a bus pulling away, bold flat orange bus tones and a soft drop shadow trailing him as the frame drifts slowly right.',
    'A marker-comp animatic ad beat: a woman with a high ponytail in a teal apron slams a frothy coffee cup onto a diner counter, steam curling upward in loose accent-yellow strokes while a barstool wobbles and the composition gently pans in.',
  ],
  'greyscale-layout': [
    "A grey-silhouetted man in a long coat and wide-brimmed hat strides down a rain-slick alley, his shadow stretching under a single overhead lamp, while a slow camera drift reveals a second figure stepping out from a doorway's dark tonal block ahead of him.",
    'In a blocked-in cathedral of tall windows, a silhouetted woman with a long braid and flowing robe climbs a wide staircase into a shaft of implied key light, pigeons scattering as tonal shapes across the frame while the camera pushes gently upward with her.',
  ],
  'intentionally-unfinished': [
    'A man with slicked-back dark hair in a rain-soaked charcoal trench coat sprints through a neon alley in one continuous composed shot, his figure and splashing puddles fully rendered and graded while the alley\'s far end stays blue-pencil sketch with a scribbled arrow reading "add steam here."',
    'A cherry-red vintage convertible drifts around a desert canyon curve as a woman with a long black braid in an olive jumpsuit grips the wheel, her face and the sunlit hood fully lit and finished while the dust plume behind resolves into graphite hatching, paper-tone cliffs and a flat handwritten note marking the tire skid.',
  ],
  'real-estate-listing': [
    'A slow gimbal walk glides through a bright open-plan kitchen where a woman in a cream blazer with a low dark ponytail slides open the glass patio door, steps onto the sunlit deck, and the camera drifts past the marble island into the landscaped backyard.',
    'A drone lifts from a midday driveway to reveal a two-story suburban home with a turquoise pool, then cuts to a level wide interior frame as a man in a light blue shirt and khakis climbs the oak staircase and pushes open the master bedroom doors.',
  ],
  'saas-product-demo': [
    'A locked screen capture of a project-management dashboard fills the frame as the cursor drags a task card from "In Review" to "Shipped," a teal progress ring animating to 100%, then cuts to a short-haired woman in a white blazer at a sunlit desk explaining the workflow to camera.',
    'An analytics SaaS demo opens on a subtle push-in as the cursor applies a date filter and revenue bars redraw upward with an annotated tooltip zooming in, then cuts to a bearded man in a gray crewneck tilting a tablet mockup in his hands to show the same report syncing on mobile.',
  ],
  'healthcare-patient-story': [
    'A silver-haired man in a soft flannel shirt sits by a sunlit living-room window recounting his heart surgery to camera, hands turning a wedding ring, then rises to water the geraniums on the sill while his wife pours coffee behind him.',
    'A young woman with short curly black hair and a yellow cardigan walks the clinic hallway with her physiotherapist, laughing as she takes unaided steps, then settles into a chair by the window and tells the camera about the day she stood up again.',
  ],
  'restaurant-menu-hero': [
    "A chef's tattooed hands ladle glossy saffron broth over a seared scallop on slate, backlit steam curling upward as tweezers place micro-basil, then the camera tracks slowly past the finished plate as golden oil beads catch the window light.",
    'Overhead, a wood-fired margherita pizza slides from the peel onto raw oak, blistered crust still smoking, as a male chef in a black apron and cropped dark hair drizzles green olive oil in a spiral and scatters torn basil that flutters into place.',
  ],
  'fitness-coaching': [
    'A male coach with a close-cropped beard in a fitted charcoal training tee kneels to demonstrate a kettlebell deadlift on the light wood floor, then rises to camera mid-explanation as the gimbal drifts to a macro of his gripping hands and planted feet.',
    'A female coach with a high dark ponytail in a teal-accented tank counts a client through slow squats beside the studio mirror, adjusting his knee alignment with a hand, then turns to camera by the sunlit window to explain the tempo cue.',
  ],
  'edtech-explainer': [
    'A young man with cropped curly hair and a mustard sweatshirt sits at a sunlit kitchen table, tapping through a coding lesson on his laptop and grinning as a floating glass-card UI insert pushes in on his progress bar filling to 100% and a badge popping open.',
    'A woman in her thirties with a dark braid and denim jacket rides a bright city bus, thumbing through language-lesson cards on her phone and mouthing new words, before we cut flat-on to a clean UI insert where a course card flips and an instructor avatar slides in with a streak counter ticking up.',
  ],
  'automotive-showroom': [
    "A pearl-white electric SUV sits centered on polished showroom concrete as the camera gimbals in a slow arc around it, the driver's door swings open and the dashboard and ambient cabin lighting wake up in sequence, then a macro push holds on the illuminated badge and quilted seat stitching under diffuse overhead LEDs.",
    'A certified pre-owned candy-red coupe rolls slowly onto the showroom floor under bright brand signage, stopping beneath a diffusion panel as a male salesperson in a navy blazer with short dark hair steps into soft focus behind it, lifts the hood, and the camera glides low across the fender to a locked hero wide.',
  ],
  'b2b-keynote': [
    'A woman with a sleek dark bob in a charcoal turtleneck strides across the minimal stage, sweeping her arm as the brand mark behind her dissolves into a full-frame cloud-security dashboard, then turns to camera mid-sentence while the hazy audience leans in and applauds.',
    'A tall man with close-cropped gray hair in a navy suit lifts a matte-black edge server from a rising pedestal as reveal light snaps on, tilting it toward the front row, then paces downstage explaining the launch while a slow zoom punches in on his face.',
  ],
  'nonprofit-cause': [
    'A woman in her fifties with silver-streaked braids and a faded blue apron stirs a steaming pot in a community kitchen, then turns to the handheld camera mid-motion and speaks about the neighbors she feeds, volunteers ladling soup behind her in warm window light.',
    'At golden hour a young male agronomist in a dusty green polo walks a row of new seedlings with two farmers, crouching to lift a handful of soil toward the lens as he explains how the irrigation well changed the season, wind moving the crop behind him.',
  ],
  'travel-destination': [
    "At dawn in the Bolivian Altiplano, a drone rises over a salt flat mirroring pink sky as a woman in a red wool shawl and long black braid walks her loaded llama across the glassy crust, then cuts close to her hands tightening the animal's woven girth.",
    "At dusk in Kyoto's Gion district, a man in a charcoal indigo apron and cropped grey hair lights paper lanterns along a wooden teahouse facade with a long taper, sparks flaring, before a slow tracking move follows steam curling from tea he pours for two guests.",
  ],
  'bathroom-counter-ugc': [
    'A woman with damp dark curls and a cream ribbed tank shakes a frosted glass serum bottle on her cluttered vanity, pumps two drops onto her fingertips beside a toothbrush and hair tie, then leans into the mirror patting it across her cheekbones under the warm vanity bar.',
    'A man with short buzzed hair and a grey t-shirt squeezes a thick white curl of scalp scrub onto his palm at the bathroom sink, works it between his fingers for a macro texture beat, then massages it into his hairline as daylight from the window catches the steamy mirror.',
  ],
};
