/**
 * Sequence Elements Schema
 * Per-sequence user-uploaded reference media (logos, product shots,
 * screenshots — and since #1559 also clips and audio) referenced in scripts by
 * uppercase token.
 */

import type { InferInsertModel, InferSelectModel } from 'drizzle-orm';
import {
  index,
  integer,
  real,
  snakeCase,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import type { SequenceElementKind } from '@/cast/element-kind';
import { generateId } from '@/platform/id';
import { sequences } from './sequences';

const VISION_STATUSES = [
  'pending',
  'analyzing',
  'completed',
  'failed',
] as const;
export type ElementVisionStatus = (typeof VISION_STATUSES)[number];

export const sequenceElements = snakeCase.table(
  'sequence_elements',
  {
    id: text()
      .$defaultFn(() => generateId())
      .primaryKey()
      .notNull(),
    sequenceId: text()
      .notNull()
      .references(() => sequences.id, { onDelete: 'cascade' }),
    // Original filename as uploaded, used to derive the token.
    uploadedFilename: text({ length: 500 }).notNull(),
    // Uppercase token used to reference this element in scripts (e.g. "LOGO", "BOTTLE").
    // Must be unique within a sequence.
    token: text({ length: 100 }).notNull(),
    // What the uploaded file IS (#1559) — never what it is for. Defaulted to
    // `image` because every row that predates #1559 was one; new rows always
    // state it (derived from the file at upload).
    kind: text().$type<SequenceElementKind>().default('image').notNull(),
    // Clip length in seconds for `video` / `audio`; null for an image (and for
    // a clip whose browser couldn't report one). A hint, not a constraint: the
    // prompt is told the length, and only speech needs the clip to cover the
    // shot.
    durationSeconds: real(),
    // Visual description generated by the vision LLM.
    description: text(),
    // Short slug tag used in prompts for consistency (e.g. "red-hex-logo").
    consistencyTag: text(),
    // Storage — the stored media for ANY kind, not just images (the column
    // names predate #1559 and renaming them buys nothing). Null for an element
    // the script analysis detected but whose reference image has not been
    // generated yet (the References stage fills it in). Reference binding skips
    // media-less elements.
    imageUrl: text(),
    imagePath: text(), // R2 key
    // Vision analysis status
    visionStatus: text()
      .$type<ElementVisionStatus>()
      .default('pending')
      .notNull(),
    visionError: text(),
    visionGeneratedAt: integer({ mode: 'timestamp' }),
    // First appearance in script (populated during scene-split reconciliation)
    firstMentionSceneId: text(),
    firstMentionText: text(),
    firstMentionLine: integer(),
    // Soft-hide from the sequence (#1108 Phase 2, undoable). Excluded from
    // default lists / element bibles; token uniqueness still counts deleted
    // rows so a restore can never collide. R2 bytes are never deleted.
    deletedAt: integer({ mode: 'timestamp' }),
    // Timestamps
    createdAt: integer({ mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
    updatedAt: integer({ mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (table) => [
    index('idx_sequence_elements_sequence_id').on(table.sequenceId),
    uniqueIndex('sequence_elements_sequence_token_key').on(
      table.sequenceId,
      table.token
    ),
  ]
);

export type SequenceElement = InferSelectModel<typeof sequenceElements>;
export type NewSequenceElement = InferInsertModel<typeof sequenceElements>;

export type SequenceElementMinimal = Pick<
  SequenceElement,
  | 'id'
  | 'token'
  | 'description'
  | 'imageUrl'
  | 'consistencyTag'
  | 'kind'
  | 'durationSeconds'
>;
