/**
 * ElevenLabs rate card (#1552).
 *
 * Unlike fal — which publishes a pricing API the nightly cron mirrors into
 * `model_pricing` — ElevenLabs exposes no machine-readable rates we ingest,
 * so this is a hand-maintained card merged into the effective pricing map at
 * read time. Merging in code rather than seeding rows keeps a fresh deploy
 * correct immediately: there is no window where TTS / Voice Design / Music
 * bill $0 because a seed step has not run (#1069's failure mode).
 *
 * The card is keyed by our own ids (`elevenlabs-tts`,
 * `elevenlabs-voice-design`, `elevenlabs-music`) and reuses the fal pricing
 * shape, so every downstream consumer — pre-flight estimation, the exact
 * charge, the /pricing page, ActionCost labels — works unchanged. The ids
 * cannot collide with leftover fal endpoint ids
 * (`fal-ai/elevenlabs/music` is the retired proxy, not this card).
 *
 * Native spend is unaudited by the #1069 fal reconcile (`recordFalUsage`
 * skips these ids), same as xAI / Google / Ark.
 *
 * RATES ARE ADVERTISED, NOT BILL-VERIFIED, and were read off
 * https://elevenlabs.io/pricing/api on **2026-09-15**. Confirm each rate
 * against a real ElevenLabs invoice before leaning on it, and re-date this
 * line when bumping.
 */

import { micros, multiplyMicros, type Microdollars } from './money';
import { seedAudioCost } from './seed-speech-pricing';
import type { EffectiveFalPricing } from '@/billing/server/fal-pricing-live';

/** Billing id for native ElevenLabs TTS (`eleven_v3` / multilingual v2). */
export const ELEVENLABS_TTS_ENDPOINT = 'elevenlabs-tts';

/** Billing id for Voice Design (`POST /v1/text-to-voice/design`). */
export const ELEVENLABS_VOICE_DESIGN_ENDPOINT = 'elevenlabs-voice-design';

/**
 * Billing id for native ElevenLabs Music (`music_v2_5` via `elevenlabsAudio`).
 * Distinct from the retired fal proxy `fal-ai/elevenlabs/music`.
 */
export const ELEVENLABS_MUSIC_ENDPOINT = 'elevenlabs-music';

/**
 * Adapter model id — the newest Eleven Music model (`ELEVENLABS_AUDIO_MODELS`
 * leads with it). v2.5 bills at the same $0.15/minute as v1 and takes the
 * same request; it enforces section durations strictly, where v1 let
 * `respect_sections_durations` relax them (we never send that flag, so the
 * only visible change is the model id — which IS part of the e2e fixture
 * match, so bumping it needs a re-record).
 */
export const ELEVENLABS_MUSIC_MODEL = 'music_v2_5' as const;

/**
 * Per-product ElevenLabs rates.
 *
 * TTS bills per character: `units = characterCount / 1000`, charged at the
 * v3 / Multilingual v2 advertised rate. We pin the HIGHER quality tier
 * deliberately — Flash/Turbo is $0.05/1K, and an under-estimate lets a team
 * spend past its balance, which is the failure mode #1069 exists to prevent.
 *
 * Voice Design is priced per call, not per character: the preview text is
 * generated by ElevenLabs (100–1000 chars × three options) and is not known
 * at estimate time. The rate over-estimates a max-length preview batch
 * (3 × 1000 chars × $0.10/1K = $0.30) so the credit gate stays conservative.
 *
 * `typicalUnitsPerCall: 1` is required: `per_call` estimation returns null
 * without a unit-count signal, which gates on the $0.10 floor instead of
 * the real price.
 */
/** Scribe v2 batch transcription (#1765): $0.22 per hour, 2026-09-23. */
const ELEVENLABS_SCRIBE_ENDPOINT = 'elevenlabs-scribe';

/** Voice isolation (#1765): $0.12 per minute, 2026-09-23. */
const ELEVENLABS_ISOLATION_ENDPOINT = 'elevenlabs-isolation';

const SCRIBE_PER_MINUTE = micros(3_667);
const ISOLATION_PER_MINUTE = micros(120_000);

/** Scribe for `seconds` of audio. */
export function scribeCost(seconds: number): Microdollars {
  return seconds > 0
    ? multiplyMicros(SCRIBE_PER_MINUTE, seconds / 60)
    : micros(0);
}

/** Voice isolation for `seconds` of audio. */
export function isolationCost(seconds: number): Microdollars {
  return seconds > 0
    ? multiplyMicros(ISOLATION_PER_MINUTE, seconds / 60)
    : micros(0);
}

/** One Voice Design call (#1553): three previews, no slot. */
export const VOICE_DESIGN_COST = micros(300_000);

/**
 * What to reserve for one new character voice, whichever provider makes it
 * (#1765). A Seed voice is three range reads — each ~35 s of Seed Audio
 * ($0.0875), its Scribe pass and ~30 s of isolation ($0.06) — about $0.45, so
 * the estimate is the dearer of the two, rounded up.
 */
export const VOICE_ESTIMATE_COST = micros(500_000);

export const ELEVENLABS_RATE_CARD: Record<string, EffectiveFalPricing> = {
  // eleven_v3 / eleven_multilingual_v2 — $0.10 per 1,000 characters.
  // Flash / Turbo is $0.05; we keep the quality-tier rate so the credit
  // gate over-estimates. Revisit if dialogue TTS switches to Flash.
  [ELEVENLABS_TTS_ENDPOINT]: {
    unitPrice: micros(100_000),
    unit: '1000 characters',
    typicalUnitsPerCall: 1,
  },
  [ELEVENLABS_VOICE_DESIGN_ENDPOINT]: {
    unitPrice: VOICE_DESIGN_COST,
    unit: 'generations',
    typicalUnitsPerCall: 1,
  },
  // Eleven Music — $0.15 per minute, rounded up. Advertised 2026-09-15.
  [ELEVENLABS_MUSIC_ENDPOINT]: {
    unitPrice: micros(150_000),
    unit: 'minutes',
  },
  [ELEVENLABS_SCRIBE_ENDPOINT]: {
    unitPrice: SCRIBE_PER_MINUTE,
    unit: 'minutes',
    typicalUnitsPerCall: 1,
  },
  [ELEVENLABS_ISOLATION_ENDPOINT]: {
    unitPrice: ISOLATION_PER_MINUTE,
    unit: 'minutes',
    typicalUnitsPerCall: 1,
  },
};

/** True when this id is priced by the card rather than by `model_pricing`. */
export function isElevenLabsPricedModel(modelId: string): boolean {
  return modelId in ELEVENLABS_RATE_CARD;
}

/**
 * ElevenLabs reports TTS usage as a character count; billing multiplies a
 * `1000 characters` unit price, so convert here rather than at the call
 * site — the denomination and the divisor have to move together.
 */
export function elevenLabsTtsUnitsBilled(
  characterCount: number | undefined
): number | undefined {
  if (characterCount == null || !Number.isFinite(characterCount)) {
    return undefined;
  }
  return characterCount / 1000;
}

/** What ElevenLabs bills for `characterCount` characters of dialogue. */
export function elevenLabsTtsCost(characterCount: number): Microdollars {
  const units = elevenLabsTtsUnitsBilled(characterCount);
  if (units == null || units <= 0) return micros(0);
  const price = ELEVENLABS_RATE_CARD[ELEVENLABS_TTS_ENDPOINT]?.unitPrice;
  if (price == null) return micros(0);
  return multiplyMicros(price, units);
}

/**
 * Seed Audio bills seconds, not characters (#1765), and a scene take runs
 * well past its words — the lab's 22 s of dialogue came back as 24–40 s. At
 * 8 characters per billed second that is $0.3125 per 1,000 characters, over
 * three times the ElevenLabs rate.
 */
const SEED_CHARS_PER_BILLED_SECOND = 8;

/**
 * Pre-flight dialogue cost from a character count. A pre-flight cannot tell
 * which provider will speak each line, so it prices the dearer one: the gate
 * must never under-estimate (#1069).
 */
export function estimateTtsCost(characterCount: number): Microdollars {
  if (!Number.isFinite(characterCount) || characterCount <= 0) {
    return micros(0);
  }
  const eleven = elevenLabsTtsCost(characterCount);
  const seed = seedAudioCost(characterCount / SEED_CHARS_PER_BILLED_SECOND);
  return eleven > seed ? eleven : seed;
}

/**
 * Conservative stand-in when pre-flight cannot see the dialogue yet
 * (storyboard before scene-split). ~200 characters is a long line; the
 * in-run reservation uses the real count.
 */
export const TYPICAL_DIALOGUE_CHARS_PER_SHOT = 200;

/**
 * Pre-flight / exact music cost from a duration. ElevenLabs bills per
 * minute rounded up (a 61s track is two minutes), same as fal's old
 * proxy — the gate and the charge have to agree.
 */
export function estimateMusicCost(durationSeconds: number): Microdollars {
  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) {
    return micros(0);
  }
  const units = Math.ceil(durationSeconds / 60);
  const price = ELEVENLABS_RATE_CARD[ELEVENLABS_MUSIC_ENDPOINT]?.unitPrice;
  if (price == null) return micros(0);
  return multiplyMicros(price, units);
}
