/**
 * ElevenLabs rate card (#1552).
 *
 * Unlike fal — which publishes a pricing API the nightly cron mirrors into
 * `model_pricing` — ElevenLabs exposes no machine-readable rates we ingest,
 * so this is a hand-maintained card merged into the effective pricing map at
 * read time. Merging in code rather than seeding rows keeps a fresh deploy
 * correct immediately: there is no window where TTS / Voice Design bill $0
 * because a seed step has not run (#1069's failure mode).
 *
 * The card is keyed by our own ids (`elevenlabs-tts`,
 * `elevenlabs-voice-design`) and reuses the fal pricing shape, so every
 * downstream consumer — pre-flight estimation, the exact charge, the
 * /pricing page, ActionCost labels — works unchanged. The ids cannot collide
 * with fal endpoint ids (`fal-ai/elevenlabs/music` is a different product).
 *
 * Native spend is unaudited by the #1069 fal reconcile (`recordFalUsage`
 * skips these ids), same as xAI / Google / Ark.
 *
 * RATES ARE ADVERTISED, NOT BILL-VERIFIED, and were read off
 * https://elevenlabs.io/pricing/api on **2026-09-11**. Confirm each rate
 * against a real ElevenLabs invoice before leaning on it, and re-date this
 * line when bumping.
 */

import { micros } from './money';
import type { EffectiveFalPricing } from '@/billing/server/fal-pricing-live';

/** Billing id for native ElevenLabs TTS (`eleven_v3` / multilingual v2). */
export const ELEVENLABS_TTS_ENDPOINT = 'elevenlabs-tts';

/** Billing id for Voice Design (`POST /v1/text-to-voice/design`). */
export const ELEVENLABS_VOICE_DESIGN_ENDPOINT = 'elevenlabs-voice-design';

/**
 * Per-product ElevenLabs rates.
 *
 * TTS bills per character: `units = characterCount / 1000`, charged at the
 * v3 / Multilingual v2 advertised rate. We pin the HIGHER quality tier
 * deliberately — Flash/Turbo is $0.05/1K, and an under-estimate lets a team
 * spend past its balance, which is the failure mode #1069 exists to prevent.
 *
 * Voice Design is priced per call, not per character: the preview text is
 * generated by ElevenLabs (100–1000 chars × three options) and is not known
 * at estimate time. The rate over-estimates a max-length preview batch
 * (3 × 1000 chars × $0.10/1K = $0.30) so the credit gate stays conservative.
 *
 * `typicalUnitsPerCall: 1` is required: `per_call` estimation returns null
 * without a unit-count signal, which gates on the $0.10 floor instead of
 * the real price.
 */
export const ELEVENLABS_RATE_CARD: Record<string, EffectiveFalPricing> = {
  // eleven_v3 / eleven_multilingual_v2 — $0.10 per 1,000 characters.
  // Flash / Turbo is $0.05; we keep the quality-tier rate so the credit
  // gate over-estimates. Revisit if dialogue TTS switches to Flash.
  [ELEVENLABS_TTS_ENDPOINT]: {
    unitPrice: micros(100_000),
    unit: '1000 characters',
    typicalUnitsPerCall: 1,
  },
  [ELEVENLABS_VOICE_DESIGN_ENDPOINT]: {
    unitPrice: micros(300_000),
    unit: 'generations',
    typicalUnitsPerCall: 1,
  },
};

/** True when this id is priced by the card rather than by `model_pricing`. */
export function isElevenLabsPricedModel(modelId: string): boolean {
  return modelId in ELEVENLABS_RATE_CARD;
}

/**
 * ElevenLabs reports TTS usage as a character count; billing multiplies a
 * `1000 characters` unit price, so convert here rather than at the call
 * site — the denomination and the divisor have to move together.
 */
export function elevenLabsTtsUnitsBilled(
  characterCount: number | undefined
): number | undefined {
  if (characterCount == null || !Number.isFinite(characterCount)) {
    return undefined;
  }
  return characterCount / 1000;
}
