/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppCreditsRouteImport } from './routes/_app/credits'
import { Route as AppDeviceRouteImport } from './routes/_app/device'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ApiTestRouteRouteImport } from './routes/api/test/route'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsLlmsDotmdRouteImport } from './routes/docs/llms[.]md'
import { Route as GiftCodeRouteImport } from './routes/gift/$code'
import { Route as MetaOgRouteImport } from './routes/meta/og'
import { Route as MetaOgGithubRouteImport } from './routes/meta/og-github'
import { Route as MetaOgLinkedinRouteImport } from './routes/meta/og-linkedin'
import { Route as R2SplatRouteImport } from './routes/r2.$'
import { Route as AppAdminModerationRouteImport } from './routes/_app/admin/moderation'
import { Route as AppAdminUsageRouteImport } from './routes/_app/admin/usage'
import { Route as AppGalleryIndexRouteImport } from './routes/_app/gallery/index'
import { Route as AppImagesIndexRouteImport } from './routes/_app/images/index'
import { Route as AppLocationsIndexRouteImport } from './routes/_app/locations/index'
import { Route as AppLocationsLocationIdRouteImport } from './routes/_app/locations/$locationId'
import { Route as AppModelsIndexRouteImport } from './routes/_app/models/index'
import { Route as AppModelsSplatRouteImport } from './routes/_app/models/$'
import { Route as AppSequencesIndexRouteImport } from './routes/_app/sequences/index'
import { Route as AppSequencesIdRouteRouteImport } from './routes/_app/sequences/$id/route'
import { Route as AppSequencesNewRouteImport } from './routes/_app/sequences/new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys'
import { Route as AppSettingsDeveloperRouteImport } from './routes/_app/settings/developer'
import { Route as AppSettingsPasskeysRouteImport } from './routes/_app/settings/passkeys'
import { Route as AppStudioIndexRouteImport } from './routes/_app/studio/index'
import { Route as AppStylesIndexRouteImport } from './routes/_app/styles/index'
import { Route as AppTalentIndexRouteImport } from './routes/_app/talent/index'
import { Route as AppTalentIdRouteImport } from './routes/_app/talent/$id'
import { Route as AppVideosIndexRouteImport } from './routes/_app/videos/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiDevMemoryRouteImport } from './routes/api/dev/memory'
import { Route as ApiOpenrouterCallbackRouteImport } from './routes/api/openrouter/callback'
import { Route as ApiStorageMultipartRouteImport } from './routes/api/storage/multipart'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiTestCharacterRouteImport } from './routes/api/test/character'
import { Route as ApiTestCleanupRouteImport } from './routes/api/test/cleanup'
import { Route as ApiTestImageRouteImport } from './routes/api/test/image'
import { Route as ApiTestLocationRouteImport } from './routes/api/test/location'
import { Route as ApiTestSequenceRouteImport } from './routes/api/test/sequence'
import { Route as ApiTestShotRouteImport } from './routes/api/test/shot'
import { Route as ApiTestStyleRouteImport } from './routes/api/test/style'
import { Route as ApiTestTalentRouteImport } from './routes/api/test/talent'
import { Route as ApiTestUserRouteImport } from './routes/api/test/user'
import { Route as ApiTestVerifyRouteImport } from './routes/api/test/verify'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1SequencesRouteImport } from './routes/api/v1/sequences'
import { Route as ApiV1StylesRouteImport } from './routes/api/v1/styles'
import { Route as AppModelsFamilySplatRouteImport } from './routes/_app/models/family/$'
import { Route as AppSequencesIdMusicRouteImport } from './routes/_app/sequences/$id/music'
import { Route as AppSequencesIdScenesRouteImport } from './routes/_app/sequences/$id/scenes'
import { Route as AppSequencesIdScriptRouteImport } from './routes/_app/sequences/$id/script'
import { Route as AppSequencesIdTheatreRouteImport } from './routes/_app/sequences/$id/theatre'
import { Route as ApiV1DeviceCodeRouteImport } from './routes/api/v1/device.code'
import { Route as ApiV1DeviceTokenRouteImport } from './routes/api/v1/device.token'
import { Route as ApiV1ScriptsEnhanceRouteImport } from './routes/api/v1/scripts.enhance'
import { Route as ApiV1SequencesIdRouteImport } from './routes/api/v1/sequences.$id'
import { Route as ApiV1StylesIdRouteImport } from './routes/api/v1/styles.$id'
import { Route as AppSequencesIdCastIndexRouteImport } from './routes/_app/sequences/$id/cast/index'
import { Route as AppSequencesIdCastCharacterIdRouteImport } from './routes/_app/sequences/$id/cast/$characterId'
import { Route as AppSequencesIdElementsIndexRouteImport } from './routes/_app/sequences/$id/elements/index'
import { Route as AppSequencesIdElementsElementIdRouteImport } from './routes/_app/sequences/$id/elements/$elementId'
import { Route as AppSequencesIdLocationsIndexRouteImport } from './routes/_app/sequences/$id/locations/index'
import { Route as AppSequencesIdLocationsLocationIdRouteImport } from './routes/_app/sequences/$id/locations/$locationId'
import { Route as ApiV1SequencesIdExportsRouteImport } from './routes/api/v1/sequences.$id.exports'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeviceRoute = AppDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRouteRoute = ApiTestRouteRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLlmsDotmdRoute = DocsLlmsDotmdRouteImport.update({
  id: '/llms.md',
  path: '/llms.md',
  getParentRoute: () => DocsRoute,
} as any)
const GiftCodeRoute = GiftCodeRouteImport.update({
  id: '/gift/$code',
  path: '/gift/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOgRoute = MetaOgRouteImport.update({
  id: '/meta/og',
  path: '/meta/og',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOgGithubRoute = MetaOgGithubRouteImport.update({
  id: '/meta/og-github',
  path: '/meta/og-github',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOgLinkedinRoute = MetaOgLinkedinRouteImport.update({
  id: '/meta/og-linkedin',
  path: '/meta/og-linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const R2SplatRoute = R2SplatRouteImport.update({
  id: '/r2/$',
  path: '/r2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminModerationRoute = AppAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsageRoute = AppAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppGalleryIndexRoute = AppGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImagesIndexRoute = AppImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsLocationIdRoute = AppLocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsSplatRoute = AppModelsSplatRouteImport.update({
  id: '/models/$',
  path: '/models/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSequencesIndexRoute = AppSequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSequencesIdRouteRoute = AppSequencesIdRouteRouteImport.update({
  id: '/sequences/$id',
  path: '/sequences/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSequencesNewRoute = AppSequencesNewRouteImport.update({
  id: '/sequences/new',
  path: '/sequences/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsDeveloperRoute = AppSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPasskeysRoute = AppSettingsPasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppStudioIndexRoute = AppStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStylesIndexRoute = AppStylesIndexRouteImport.update({
  id: '/styles/',
  path: '/styles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTalentIndexRoute = AppTalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTalentIdRoute = AppTalentIdRouteImport.update({
  id: '/talent/$id',
  path: '/talent/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVideosIndexRoute = AppVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevMemoryRoute = ApiDevMemoryRouteImport.update({
  id: '/api/dev/memory',
  path: '/api/dev/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterCallbackRoute = ApiOpenrouterCallbackRouteImport.update({
  id: '/api/openrouter/callback',
  path: '/api/openrouter/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageMultipartRoute = ApiStorageMultipartRouteImport.update({
  id: '/api/storage/multipart',
  path: '/api/storage/multipart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCharacterRoute = ApiTestCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestCleanupRoute = ApiTestCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestImageRoute = ApiTestImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestLocationRoute = ApiTestLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestSequenceRoute = ApiTestSequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestShotRoute = ApiTestShotRouteImport.update({
  id: '/shot',
  path: '/shot',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestStyleRoute = ApiTestStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestTalentRoute = ApiTestTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestUserRoute = ApiTestUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestVerifyRoute = ApiTestVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SequencesRoute = ApiV1SequencesRouteImport.update({
  id: '/api/v1/sequences',
  path: '/api/v1/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StylesRoute = ApiV1StylesRouteImport.update({
  id: '/api/v1/styles',
  path: '/api/v1/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsFamilySplatRoute = AppModelsFamilySplatRouteImport.update({
  id: '/models/family/$',
  path: '/models/family/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSequencesIdMusicRoute = AppSequencesIdMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppSequencesIdRouteRoute,
} as any)
const AppSequencesIdScenesRoute = AppSequencesIdScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AppSequencesIdRouteRoute,
} as any)
const AppSequencesIdScriptRoute = AppSequencesIdScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => AppSequencesIdRouteRoute,
} as any)
const AppSequencesIdTheatreRoute = AppSequencesIdTheatreRouteImport.update({
  id: '/theatre',
  path: '/theatre',
  getParentRoute: () => AppSequencesIdRouteRoute,
} as any)
const ApiV1DeviceCodeRoute = ApiV1DeviceCodeRouteImport.update({
  id: '/api/v1/device/code',
  path: '/api/v1/device/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceTokenRoute = ApiV1DeviceTokenRouteImport.update({
  id: '/api/v1/device/token',
  path: '/api/v1/device/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScriptsEnhanceRoute = ApiV1ScriptsEnhanceRouteImport.update({
  id: '/api/v1/scripts/enhance',
  path: '/api/v1/scripts/enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SequencesIdRoute = ApiV1SequencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1SequencesRoute,
} as any)
const ApiV1StylesIdRoute = ApiV1StylesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1StylesRoute,
} as any)
const AppSequencesIdCastIndexRoute = AppSequencesIdCastIndexRouteImport.update({
  id: '/cast/',
  path: '/cast/',
  getParentRoute: () => AppSequencesIdRouteRoute,
} as any)
const AppSequencesIdCastCharacterIdRoute =
  AppSequencesIdCastCharacterIdRouteImport.update({
    id: '/cast/$characterId',
    path: '/cast/$characterId',
    getParentRoute: () => AppSequencesIdRouteRoute,
  } as any)
const AppSequencesIdElementsIndexRoute =
  AppSequencesIdElementsIndexRouteImport.update({
    id: '/elements/',
    path: '/elements/',
    getParentRoute: () => AppSequencesIdRouteRoute,
  } as any)
const AppSequencesIdElementsElementIdRoute =
  AppSequencesIdElementsElementIdRouteImport.update({
    id: '/elements/$elementId',
    path: '/elements/$elementId',
    getParentRoute: () => AppSequencesIdRouteRoute,
  } as any)
const AppSequencesIdLocationsIndexRoute =
  AppSequencesIdLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AppSequencesIdRouteRoute,
  } as any)
const AppSequencesIdLocationsLocationIdRoute =
  AppSequencesIdLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AppSequencesIdRouteRoute,
  } as any)
const ApiV1SequencesIdExportsRoute = ApiV1SequencesIdExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ApiV1SequencesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/credits': typeof AppCreditsRoute
  '/device': typeof AppDeviceRoute
  '/pricing': typeof AppPricingRoute
  '/privacy': typeof AppPrivacyRoute
  '/report': typeof AppReportRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/r2/$': typeof R2SplatRoute
  '/docs/': typeof DocsIndexRoute
  '/sequences/$id': typeof AppSequencesIdRouteRouteWithChildren
  '/admin/moderation': typeof AppAdminModerationRoute
  '/admin/usage': typeof AppAdminUsageRoute
  '/locations/$locationId': typeof AppLocationsLocationIdRoute
  '/models/$': typeof AppModelsSplatRoute
  '/sequences/new': typeof AppSequencesNewRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/developer': typeof AppSettingsDeveloperRoute
  '/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/talent/$id': typeof AppTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/multipart': typeof ApiStorageMultipartRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/shot': typeof ApiTestShotRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/sequences': typeof ApiV1SequencesRouteWithChildren
  '/api/v1/styles': typeof ApiV1StylesRouteWithChildren
  '/gallery/': typeof AppGalleryIndexRoute
  '/images/': typeof AppImagesIndexRoute
  '/locations/': typeof AppLocationsIndexRoute
  '/models/': typeof AppModelsIndexRoute
  '/sequences/': typeof AppSequencesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/studio/': typeof AppStudioIndexRoute
  '/styles/': typeof AppStylesIndexRoute
  '/talent/': typeof AppTalentIndexRoute
  '/videos/': typeof AppVideosIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/models/family/$': typeof AppModelsFamilySplatRoute
  '/sequences/$id/music': typeof AppSequencesIdMusicRoute
  '/sequences/$id/scenes': typeof AppSequencesIdScenesRoute
  '/sequences/$id/script': typeof AppSequencesIdScriptRoute
  '/sequences/$id/theatre': typeof AppSequencesIdTheatreRoute
  '/api/v1/device/code': typeof ApiV1DeviceCodeRoute
  '/api/v1/device/token': typeof ApiV1DeviceTokenRoute
  '/api/v1/scripts/enhance': typeof ApiV1ScriptsEnhanceRoute
  '/api/v1/sequences/$id': typeof ApiV1SequencesIdRouteWithChildren
  '/api/v1/styles/$id': typeof ApiV1StylesIdRoute
  '/sequences/$id/cast/$characterId': typeof AppSequencesIdCastCharacterIdRoute
  '/sequences/$id/elements/$elementId': typeof AppSequencesIdElementsElementIdRoute
  '/sequences/$id/locations/$locationId': typeof AppSequencesIdLocationsLocationIdRoute
  '/api/v1/sequences/$id/exports': typeof ApiV1SequencesIdExportsRoute
  '/sequences/$id/cast/': typeof AppSequencesIdCastIndexRoute
  '/sequences/$id/elements/': typeof AppSequencesIdElementsIndexRoute
  '/sequences/$id/locations/': typeof AppSequencesIdLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/credits': typeof AppCreditsRoute
  '/device': typeof AppDeviceRoute
  '/pricing': typeof AppPricingRoute
  '/privacy': typeof AppPrivacyRoute
  '/report': typeof AppReportRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/r2/$': typeof R2SplatRoute
  '/docs': typeof DocsIndexRoute
  '/sequences/$id': typeof AppSequencesIdRouteRouteWithChildren
  '/admin/moderation': typeof AppAdminModerationRoute
  '/admin/usage': typeof AppAdminUsageRoute
  '/locations/$locationId': typeof AppLocationsLocationIdRoute
  '/models/$': typeof AppModelsSplatRoute
  '/sequences/new': typeof AppSequencesNewRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/developer': typeof AppSettingsDeveloperRoute
  '/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/talent/$id': typeof AppTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/multipart': typeof ApiStorageMultipartRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/shot': typeof ApiTestShotRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/sequences': typeof ApiV1SequencesRouteWithChildren
  '/api/v1/styles': typeof ApiV1StylesRouteWithChildren
  '/gallery': typeof AppGalleryIndexRoute
  '/images': typeof AppImagesIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/models': typeof AppModelsIndexRoute
  '/sequences': typeof AppSequencesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/studio': typeof AppStudioIndexRoute
  '/styles': typeof AppStylesIndexRoute
  '/talent': typeof AppTalentIndexRoute
  '/videos': typeof AppVideosIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/models/family/$': typeof AppModelsFamilySplatRoute
  '/sequences/$id/music': typeof AppSequencesIdMusicRoute
  '/sequences/$id/scenes': typeof AppSequencesIdScenesRoute
  '/sequences/$id/script': typeof AppSequencesIdScriptRoute
  '/sequences/$id/theatre': typeof AppSequencesIdTheatreRoute
  '/api/v1/device/code': typeof ApiV1DeviceCodeRoute
  '/api/v1/device/token': typeof ApiV1DeviceTokenRoute
  '/api/v1/scripts/enhance': typeof ApiV1ScriptsEnhanceRoute
  '/api/v1/sequences/$id': typeof ApiV1SequencesIdRouteWithChildren
  '/api/v1/styles/$id': typeof ApiV1StylesIdRoute
  '/sequences/$id/cast/$characterId': typeof AppSequencesIdCastCharacterIdRoute
  '/sequences/$id/elements/$elementId': typeof AppSequencesIdElementsElementIdRoute
  '/sequences/$id/locations/$locationId': typeof AppSequencesIdLocationsLocationIdRoute
  '/api/v1/sequences/$id/exports': typeof ApiV1SequencesIdExportsRoute
  '/sequences/$id/cast': typeof AppSequencesIdCastIndexRoute
  '/sequences/$id/elements': typeof AppSequencesIdElementsIndexRoute
  '/sequences/$id/locations': typeof AppSequencesIdLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/_app/credits': typeof AppCreditsRoute
  '/_app/device': typeof AppDeviceRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/report': typeof AppReportRoute
  '/_app/terms': typeof AppTermsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/r2/$': typeof R2SplatRoute
  '/_app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_app/sequences/$id': typeof AppSequencesIdRouteRouteWithChildren
  '/_app/admin/moderation': typeof AppAdminModerationRoute
  '/_app/admin/usage': typeof AppAdminUsageRoute
  '/_app/locations/$locationId': typeof AppLocationsLocationIdRoute
  '/_app/models/$': typeof AppModelsSplatRoute
  '/_app/sequences/new': typeof AppSequencesNewRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/developer': typeof AppSettingsDeveloperRoute
  '/_app/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/_app/talent/$id': typeof AppTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/multipart': typeof ApiStorageMultipartRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/shot': typeof ApiTestShotRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/sequences': typeof ApiV1SequencesRouteWithChildren
  '/api/v1/styles': typeof ApiV1StylesRouteWithChildren
  '/_app/gallery/': typeof AppGalleryIndexRoute
  '/_app/images/': typeof AppImagesIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/models/': typeof AppModelsIndexRoute
  '/_app/sequences/': typeof AppSequencesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/studio/': typeof AppStudioIndexRoute
  '/_app/styles/': typeof AppStylesIndexRoute
  '/_app/talent/': typeof AppTalentIndexRoute
  '/_app/videos/': typeof AppVideosIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/_app/models/family/$': typeof AppModelsFamilySplatRoute
  '/_app/sequences/$id/music': typeof AppSequencesIdMusicRoute
  '/_app/sequences/$id/scenes': typeof AppSequencesIdScenesRoute
  '/_app/sequences/$id/script': typeof AppSequencesIdScriptRoute
  '/_app/sequences/$id/theatre': typeof AppSequencesIdTheatreRoute
  '/api/v1/device/code': typeof ApiV1DeviceCodeRoute
  '/api/v1/device/token': typeof ApiV1DeviceTokenRoute
  '/api/v1/scripts/enhance': typeof ApiV1ScriptsEnhanceRoute
  '/api/v1/sequences/$id': typeof ApiV1SequencesIdRouteWithChildren
  '/api/v1/styles/$id': typeof ApiV1StylesIdRoute
  '/_app/sequences/$id/cast/$characterId': typeof AppSequencesIdCastCharacterIdRoute
  '/_app/sequences/$id/elements/$elementId': typeof AppSequencesIdElementsElementIdRoute
  '/_app/sequences/$id/locations/$locationId': typeof AppSequencesIdLocationsLocationIdRoute
  '/api/v1/sequences/$id/exports': typeof ApiV1SequencesIdExportsRoute
  '/_app/sequences/$id/cast/': typeof AppSequencesIdCastIndexRoute
  '/_app/sequences/$id/elements/': typeof AppSequencesIdElementsIndexRoute
  '/_app/sequences/$id/locations/': typeof AppSequencesIdLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/settings'
    | '/api/test'
    | '/credits'
    | '/device'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/login'
    | '/verify'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/faq'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/r2/$'
    | '/docs/'
    | '/sequences/$id'
    | '/admin/moderation'
    | '/admin/usage'
    | '/locations/$locationId'
    | '/models/$'
    | '/sequences/new'
    | '/settings/api-keys'
    | '/settings/developer'
    | '/settings/passkeys'
    | '/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/multipart'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/shot'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/v1/openapi.json'
    | '/api/v1/sequences'
    | '/api/v1/styles'
    | '/gallery/'
    | '/images/'
    | '/locations/'
    | '/models/'
    | '/sequences/'
    | '/settings/'
    | '/studio/'
    | '/styles/'
    | '/talent/'
    | '/videos/'
    | '/api/v1/'
    | '/models/family/$'
    | '/sequences/$id/music'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/sequences/$id/theatre'
    | '/api/v1/device/code'
    | '/api/v1/device/token'
    | '/api/v1/scripts/enhance'
    | '/api/v1/sequences/$id'
    | '/api/v1/styles/$id'
    | '/sequences/$id/cast/$characterId'
    | '/sequences/$id/elements/$elementId'
    | '/sequences/$id/locations/$locationId'
    | '/api/v1/sequences/$id/exports'
    | '/sequences/$id/cast/'
    | '/sequences/$id/elements/'
    | '/sequences/$id/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/api/test'
    | '/credits'
    | '/device'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/login'
    | '/verify'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/faq'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/r2/$'
    | '/docs'
    | '/sequences/$id'
    | '/admin/moderation'
    | '/admin/usage'
    | '/locations/$locationId'
    | '/models/$'
    | '/sequences/new'
    | '/settings/api-keys'
    | '/settings/developer'
    | '/settings/passkeys'
    | '/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/multipart'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/shot'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/v1/openapi.json'
    | '/api/v1/sequences'
    | '/api/v1/styles'
    | '/gallery'
    | '/images'
    | '/locations'
    | '/models'
    | '/sequences'
    | '/settings'
    | '/studio'
    | '/styles'
    | '/talent'
    | '/videos'
    | '/api/v1'
    | '/models/family/$'
    | '/sequences/$id/music'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/sequences/$id/theatre'
    | '/api/v1/device/code'
    | '/api/v1/device/token'
    | '/api/v1/scripts/enhance'
    | '/api/v1/sequences/$id'
    | '/api/v1/styles/$id'
    | '/sequences/$id/cast/$characterId'
    | '/sequences/$id/elements/$elementId'
    | '/sequences/$id/locations/$locationId'
    | '/api/v1/sequences/$id/exports'
    | '/sequences/$id/cast'
    | '/sequences/$id/elements'
    | '/sequences/$id/locations'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/docs'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/settings'
    | '/api/test'
    | '/_app/credits'
    | '/_app/device'
    | '/_app/pricing'
    | '/_app/privacy'
    | '/_app/report'
    | '/_app/terms'
    | '/_auth/login'
    | '/_auth/verify'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/faq'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/r2/$'
    | '/_app/'
    | '/docs/'
    | '/_app/sequences/$id'
    | '/_app/admin/moderation'
    | '/_app/admin/usage'
    | '/_app/locations/$locationId'
    | '/_app/models/$'
    | '/_app/sequences/new'
    | '/_app/settings/api-keys'
    | '/_app/settings/developer'
    | '/_app/settings/passkeys'
    | '/_app/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/multipart'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/shot'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/v1/openapi.json'
    | '/api/v1/sequences'
    | '/api/v1/styles'
    | '/_app/gallery/'
    | '/_app/images/'
    | '/_app/locations/'
    | '/_app/models/'
    | '/_app/sequences/'
    | '/_app/settings/'
    | '/_app/studio/'
    | '/_app/styles/'
    | '/_app/talent/'
    | '/_app/videos/'
    | '/api/v1/'
    | '/_app/models/family/$'
    | '/_app/sequences/$id/music'
    | '/_app/sequences/$id/scenes'
    | '/_app/sequences/$id/script'
    | '/_app/sequences/$id/theatre'
    | '/api/v1/device/code'
    | '/api/v1/device/token'
    | '/api/v1/scripts/enhance'
    | '/api/v1/sequences/$id'
    | '/api/v1/styles/$id'
    | '/_app/sequences/$id/cast/$characterId'
    | '/_app/sequences/$id/elements/$elementId'
    | '/_app/sequences/$id/locations/$locationId'
    | '/api/v1/sequences/$id/exports'
    | '/_app/sequences/$id/cast/'
    | '/_app/sequences/$id/elements/'
    | '/_app/sequences/$id/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTestRouteRoute: typeof ApiTestRouteRouteWithChildren
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  GiftCodeRoute: typeof GiftCodeRoute
  MetaOgRoute: typeof MetaOgRoute
  MetaOgGithubRoute: typeof MetaOgGithubRoute
  MetaOgLinkedinRoute: typeof MetaOgLinkedinRoute
  R2SplatRoute: typeof R2SplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiDevMemoryRoute: typeof ApiDevMemoryRoute
  ApiOpenrouterCallbackRoute: typeof ApiOpenrouterCallbackRoute
  ApiStorageMultipartRoute: typeof ApiStorageMultipartRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1SequencesRoute: typeof ApiV1SequencesRouteWithChildren
  ApiV1StylesRoute: typeof ApiV1StylesRouteWithChildren
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiV1DeviceCodeRoute: typeof ApiV1DeviceCodeRoute
  ApiV1DeviceTokenRoute: typeof ApiV1DeviceTokenRoute
  ApiV1ScriptsEnhanceRoute: typeof ApiV1ScriptsEnhanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/llms.md': {
      id: '/docs/llms.md'
      path: '/llms.md'
      fullPath: '/docs/llms.md'
      preLoaderRoute: typeof DocsLlmsDotmdRouteImport
      parentRoute: typeof DocsRoute
    }
    '/gift/$code': {
      id: '/gift/$code'
      path: '/gift/$code'
      fullPath: '/gift/$code'
      preLoaderRoute: typeof GiftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/og': {
      id: '/meta/og'
      path: '/meta/og'
      fullPath: '/meta/og'
      preLoaderRoute: typeof MetaOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/og-github': {
      id: '/meta/og-github'
      path: '/meta/og-github'
      fullPath: '/meta/og-github'
      preLoaderRoute: typeof MetaOgGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/og-linkedin': {
      id: '/meta/og-linkedin'
      path: '/meta/og-linkedin'
      fullPath: '/meta/og-linkedin'
      preLoaderRoute: typeof MetaOgLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2/$': {
      id: '/r2/$'
      path: '/r2/$'
      fullPath: '/r2/$'
      preLoaderRoute: typeof R2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/moderation': {
      id: '/_app/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AppAdminModerationRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/usage': {
      id: '/_app/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AppAdminUsageRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/gallery/': {
      id: '/_app/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof AppGalleryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/images/': {
      id: '/_app/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof AppImagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locations/$locationId': {
      id: '/_app/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AppLocationsLocationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/': {
      id: '/_app/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/$': {
      id: '/_app/models/$'
      path: '/models/$'
      fullPath: '/models/$'
      preLoaderRoute: typeof AppModelsSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sequences/': {
      id: '/_app/sequences/'
      path: '/sequences'
      fullPath: '/sequences/'
      preLoaderRoute: typeof AppSequencesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sequences/$id': {
      id: '/_app/sequences/$id'
      path: '/sequences/$id'
      fullPath: '/sequences/$id'
      preLoaderRoute: typeof AppSequencesIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sequences/new': {
      id: '/_app/sequences/new'
      path: '/sequences/new'
      fullPath: '/sequences/new'
      preLoaderRoute: typeof AppSequencesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/developer': {
      id: '/_app/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AppSettingsDeveloperRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/passkeys': {
      id: '/_app/settings/passkeys'
      path: '/passkeys'
      fullPath: '/settings/passkeys'
      preLoaderRoute: typeof AppSettingsPasskeysRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/studio/': {
      id: '/_app/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AppStudioIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/styles/': {
      id: '/_app/styles/'
      path: '/styles'
      fullPath: '/styles/'
      preLoaderRoute: typeof AppStylesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/talent/': {
      id: '/_app/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof AppTalentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/talent/$id': {
      id: '/_app/talent/$id'
      path: '/talent/$id'
      fullPath: '/talent/$id'
      preLoaderRoute: typeof AppTalentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/videos/': {
      id: '/_app/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AppVideosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/memory': {
      id: '/api/dev/memory'
      path: '/api/dev/memory'
      fullPath: '/api/dev/memory'
      preLoaderRoute: typeof ApiDevMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter/callback': {
      id: '/api/openrouter/callback'
      path: '/api/openrouter/callback'
      fullPath: '/api/openrouter/callback'
      preLoaderRoute: typeof ApiOpenrouterCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/multipart': {
      id: '/api/storage/multipart'
      path: '/api/storage/multipart'
      fullPath: '/api/storage/multipart'
      preLoaderRoute: typeof ApiStorageMultipartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/character': {
      id: '/api/test/character'
      path: '/character'
      fullPath: '/api/test/character'
      preLoaderRoute: typeof ApiTestCharacterRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/cleanup': {
      id: '/api/test/cleanup'
      path: '/cleanup'
      fullPath: '/api/test/cleanup'
      preLoaderRoute: typeof ApiTestCleanupRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/image': {
      id: '/api/test/image'
      path: '/image'
      fullPath: '/api/test/image'
      preLoaderRoute: typeof ApiTestImageRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/location': {
      id: '/api/test/location'
      path: '/location'
      fullPath: '/api/test/location'
      preLoaderRoute: typeof ApiTestLocationRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/sequence': {
      id: '/api/test/sequence'
      path: '/sequence'
      fullPath: '/api/test/sequence'
      preLoaderRoute: typeof ApiTestSequenceRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/shot': {
      id: '/api/test/shot'
      path: '/shot'
      fullPath: '/api/test/shot'
      preLoaderRoute: typeof ApiTestShotRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/style': {
      id: '/api/test/style'
      path: '/style'
      fullPath: '/api/test/style'
      preLoaderRoute: typeof ApiTestStyleRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/talent': {
      id: '/api/test/talent'
      path: '/talent'
      fullPath: '/api/test/talent'
      preLoaderRoute: typeof ApiTestTalentRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/user': {
      id: '/api/test/user'
      path: '/user'
      fullPath: '/api/test/user'
      preLoaderRoute: typeof ApiTestUserRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/verify': {
      id: '/api/test/verify'
      path: '/verify'
      fullPath: '/api/test/verify'
      preLoaderRoute: typeof ApiTestVerifyRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sequences': {
      id: '/api/v1/sequences'
      path: '/api/v1/sequences'
      fullPath: '/api/v1/sequences'
      preLoaderRoute: typeof ApiV1SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/styles': {
      id: '/api/v1/styles'
      path: '/api/v1/styles'
      fullPath: '/api/v1/styles'
      preLoaderRoute: typeof ApiV1StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/models/family/$': {
      id: '/_app/models/family/$'
      path: '/models/family/$'
      fullPath: '/models/family/$'
      preLoaderRoute: typeof AppModelsFamilySplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sequences/$id/music': {
      id: '/_app/sequences/$id/music'
      path: '/music'
      fullPath: '/sequences/$id/music'
      preLoaderRoute: typeof AppSequencesIdMusicRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/scenes': {
      id: '/_app/sequences/$id/scenes'
      path: '/scenes'
      fullPath: '/sequences/$id/scenes'
      preLoaderRoute: typeof AppSequencesIdScenesRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/script': {
      id: '/_app/sequences/$id/script'
      path: '/script'
      fullPath: '/sequences/$id/script'
      preLoaderRoute: typeof AppSequencesIdScriptRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/theatre': {
      id: '/_app/sequences/$id/theatre'
      path: '/theatre'
      fullPath: '/sequences/$id/theatre'
      preLoaderRoute: typeof AppSequencesIdTheatreRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/api/v1/device/code': {
      id: '/api/v1/device/code'
      path: '/api/v1/device/code'
      fullPath: '/api/v1/device/code'
      preLoaderRoute: typeof ApiV1DeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/token': {
      id: '/api/v1/device/token'
      path: '/api/v1/device/token'
      fullPath: '/api/v1/device/token'
      preLoaderRoute: typeof ApiV1DeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scripts/enhance': {
      id: '/api/v1/scripts/enhance'
      path: '/api/v1/scripts/enhance'
      fullPath: '/api/v1/scripts/enhance'
      preLoaderRoute: typeof ApiV1ScriptsEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sequences/$id': {
      id: '/api/v1/sequences/$id'
      path: '/$id'
      fullPath: '/api/v1/sequences/$id'
      preLoaderRoute: typeof ApiV1SequencesIdRouteImport
      parentRoute: typeof ApiV1SequencesRoute
    }
    '/api/v1/styles/$id': {
      id: '/api/v1/styles/$id'
      path: '/$id'
      fullPath: '/api/v1/styles/$id'
      preLoaderRoute: typeof ApiV1StylesIdRouteImport
      parentRoute: typeof ApiV1StylesRoute
    }
    '/_app/sequences/$id/cast/': {
      id: '/_app/sequences/$id/cast/'
      path: '/cast'
      fullPath: '/sequences/$id/cast/'
      preLoaderRoute: typeof AppSequencesIdCastIndexRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/cast/$characterId': {
      id: '/_app/sequences/$id/cast/$characterId'
      path: '/cast/$characterId'
      fullPath: '/sequences/$id/cast/$characterId'
      preLoaderRoute: typeof AppSequencesIdCastCharacterIdRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/elements/': {
      id: '/_app/sequences/$id/elements/'
      path: '/elements'
      fullPath: '/sequences/$id/elements/'
      preLoaderRoute: typeof AppSequencesIdElementsIndexRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/elements/$elementId': {
      id: '/_app/sequences/$id/elements/$elementId'
      path: '/elements/$elementId'
      fullPath: '/sequences/$id/elements/$elementId'
      preLoaderRoute: typeof AppSequencesIdElementsElementIdRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/locations/': {
      id: '/_app/sequences/$id/locations/'
      path: '/locations'
      fullPath: '/sequences/$id/locations/'
      preLoaderRoute: typeof AppSequencesIdLocationsIndexRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/_app/sequences/$id/locations/$locationId': {
      id: '/_app/sequences/$id/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/sequences/$id/locations/$locationId'
      preLoaderRoute: typeof AppSequencesIdLocationsLocationIdRouteImport
      parentRoute: typeof AppSequencesIdRouteRoute
    }
    '/api/v1/sequences/$id/exports': {
      id: '/api/v1/sequences/$id/exports'
      path: '/exports'
      fullPath: '/api/v1/sequences/$id/exports'
      preLoaderRoute: typeof ApiV1SequencesIdExportsRouteImport
      parentRoute: typeof ApiV1SequencesIdRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminModerationRoute: typeof AppAdminModerationRoute
  AppAdminUsageRoute: typeof AppAdminUsageRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminModerationRoute: AppAdminModerationRoute,
  AppAdminUsageRoute: AppAdminUsageRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsDeveloperRoute: typeof AppSettingsDeveloperRoute
  AppSettingsPasskeysRoute: typeof AppSettingsPasskeysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsDeveloperRoute: AppSettingsDeveloperRoute,
  AppSettingsPasskeysRoute: AppSettingsPasskeysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppSequencesIdRouteRouteChildren {
  AppSequencesIdMusicRoute: typeof AppSequencesIdMusicRoute
  AppSequencesIdScenesRoute: typeof AppSequencesIdScenesRoute
  AppSequencesIdScriptRoute: typeof AppSequencesIdScriptRoute
  AppSequencesIdTheatreRoute: typeof AppSequencesIdTheatreRoute
  AppSequencesIdCastCharacterIdRoute: typeof AppSequencesIdCastCharacterIdRoute
  AppSequencesIdElementsElementIdRoute: typeof AppSequencesIdElementsElementIdRoute
  AppSequencesIdLocationsLocationIdRoute: typeof AppSequencesIdLocationsLocationIdRoute
  AppSequencesIdCastIndexRoute: typeof AppSequencesIdCastIndexRoute
  AppSequencesIdElementsIndexRoute: typeof AppSequencesIdElementsIndexRoute
  AppSequencesIdLocationsIndexRoute: typeof AppSequencesIdLocationsIndexRoute
}

const AppSequencesIdRouteRouteChildren: AppSequencesIdRouteRouteChildren = {
  AppSequencesIdMusicRoute: AppSequencesIdMusicRoute,
  AppSequencesIdScenesRoute: AppSequencesIdScenesRoute,
  AppSequencesIdScriptRoute: AppSequencesIdScriptRoute,
  AppSequencesIdTheatreRoute: AppSequencesIdTheatreRoute,
  AppSequencesIdCastCharacterIdRoute: AppSequencesIdCastCharacterIdRoute,
  AppSequencesIdElementsElementIdRoute: AppSequencesIdElementsElementIdRoute,
  AppSequencesIdLocationsLocationIdRoute:
    AppSequencesIdLocationsLocationIdRoute,
  AppSequencesIdCastIndexRoute: AppSequencesIdCastIndexRoute,
  AppSequencesIdElementsIndexRoute: AppSequencesIdElementsIndexRoute,
  AppSequencesIdLocationsIndexRoute: AppSequencesIdLocationsIndexRoute,
}

const AppSequencesIdRouteRouteWithChildren =
  AppSequencesIdRouteRoute._addFileChildren(AppSequencesIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppCreditsRoute: typeof AppCreditsRoute
  AppDeviceRoute: typeof AppDeviceRoute
  AppPricingRoute: typeof AppPricingRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppReportRoute: typeof AppReportRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSequencesIdRouteRoute: typeof AppSequencesIdRouteRouteWithChildren
  AppLocationsLocationIdRoute: typeof AppLocationsLocationIdRoute
  AppModelsSplatRoute: typeof AppModelsSplatRoute
  AppSequencesNewRoute: typeof AppSequencesNewRoute
  AppTalentIdRoute: typeof AppTalentIdRoute
  AppGalleryIndexRoute: typeof AppGalleryIndexRoute
  AppImagesIndexRoute: typeof AppImagesIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
  AppSequencesIndexRoute: typeof AppSequencesIndexRoute
  AppStudioIndexRoute: typeof AppStudioIndexRoute
  AppStylesIndexRoute: typeof AppStylesIndexRoute
  AppTalentIndexRoute: typeof AppTalentIndexRoute
  AppVideosIndexRoute: typeof AppVideosIndexRoute
  AppModelsFamilySplatRoute: typeof AppModelsFamilySplatRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppCreditsRoute: AppCreditsRoute,
  AppDeviceRoute: AppDeviceRoute,
  AppPricingRoute: AppPricingRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppReportRoute: AppReportRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSequencesIdRouteRoute: AppSequencesIdRouteRouteWithChildren,
  AppLocationsLocationIdRoute: AppLocationsLocationIdRoute,
  AppModelsSplatRoute: AppModelsSplatRoute,
  AppSequencesNewRoute: AppSequencesNewRoute,
  AppTalentIdRoute: AppTalentIdRoute,
  AppGalleryIndexRoute: AppGalleryIndexRoute,
  AppImagesIndexRoute: AppImagesIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
  AppSequencesIndexRoute: AppSequencesIndexRoute,
  AppStudioIndexRoute: AppStudioIndexRoute,
  AppStylesIndexRoute: AppStylesIndexRoute,
  AppTalentIndexRoute: AppTalentIndexRoute,
  AppVideosIndexRoute: AppVideosIndexRoute,
  AppModelsFamilySplatRoute: AppModelsFamilySplatRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsLlmsDotmdRoute: typeof DocsLlmsDotmdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsLlmsDotmdRoute: DocsLlmsDotmdRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiTestRouteRouteChildren {
  ApiTestCharacterRoute: typeof ApiTestCharacterRoute
  ApiTestCleanupRoute: typeof ApiTestCleanupRoute
  ApiTestImageRoute: typeof ApiTestImageRoute
  ApiTestLocationRoute: typeof ApiTestLocationRoute
  ApiTestSequenceRoute: typeof ApiTestSequenceRoute
  ApiTestShotRoute: typeof ApiTestShotRoute
  ApiTestStyleRoute: typeof ApiTestStyleRoute
  ApiTestTalentRoute: typeof ApiTestTalentRoute
  ApiTestUserRoute: typeof ApiTestUserRoute
  ApiTestVerifyRoute: typeof ApiTestVerifyRoute
}

const ApiTestRouteRouteChildren: ApiTestRouteRouteChildren = {
  ApiTestCharacterRoute: ApiTestCharacterRoute,
  ApiTestCleanupRoute: ApiTestCleanupRoute,
  ApiTestImageRoute: ApiTestImageRoute,
  ApiTestLocationRoute: ApiTestLocationRoute,
  ApiTestSequenceRoute: ApiTestSequenceRoute,
  ApiTestShotRoute: ApiTestShotRoute,
  ApiTestStyleRoute: ApiTestStyleRoute,
  ApiTestTalentRoute: ApiTestTalentRoute,
  ApiTestUserRoute: ApiTestUserRoute,
  ApiTestVerifyRoute: ApiTestVerifyRoute,
}

const ApiTestRouteRouteWithChildren = ApiTestRouteRoute._addFileChildren(
  ApiTestRouteRouteChildren,
)

interface ApiV1SequencesIdRouteChildren {
  ApiV1SequencesIdExportsRoute: typeof ApiV1SequencesIdExportsRoute
}

const ApiV1SequencesIdRouteChildren: ApiV1SequencesIdRouteChildren = {
  ApiV1SequencesIdExportsRoute: ApiV1SequencesIdExportsRoute,
}

const ApiV1SequencesIdRouteWithChildren =
  ApiV1SequencesIdRoute._addFileChildren(ApiV1SequencesIdRouteChildren)

interface ApiV1SequencesRouteChildren {
  ApiV1SequencesIdRoute: typeof ApiV1SequencesIdRouteWithChildren
}

const ApiV1SequencesRouteChildren: ApiV1SequencesRouteChildren = {
  ApiV1SequencesIdRoute: ApiV1SequencesIdRouteWithChildren,
}

const ApiV1SequencesRouteWithChildren = ApiV1SequencesRoute._addFileChildren(
  ApiV1SequencesRouteChildren,
)

interface ApiV1StylesRouteChildren {
  ApiV1StylesIdRoute: typeof ApiV1StylesIdRoute
}

const ApiV1StylesRouteChildren: ApiV1StylesRouteChildren = {
  ApiV1StylesIdRoute: ApiV1StylesIdRoute,
}

const ApiV1StylesRouteWithChildren = ApiV1StylesRoute._addFileChildren(
  ApiV1StylesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTestRouteRoute: ApiTestRouteRouteWithChildren,
  ApiRealtimeRoute: ApiRealtimeRoute,
  GiftCodeRoute: GiftCodeRoute,
  MetaOgRoute: MetaOgRoute,
  MetaOgGithubRoute: MetaOgGithubRoute,
  MetaOgLinkedinRoute: MetaOgLinkedinRoute,
  R2SplatRoute: R2SplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiDevMemoryRoute: ApiDevMemoryRoute,
  ApiOpenrouterCallbackRoute: ApiOpenrouterCallbackRoute,
  ApiStorageMultipartRoute: ApiStorageMultipartRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1SequencesRoute: ApiV1SequencesRouteWithChildren,
  ApiV1StylesRoute: ApiV1StylesRouteWithChildren,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiV1DeviceCodeRoute: ApiV1DeviceCodeRoute,
  ApiV1DeviceTokenRoute: ApiV1DeviceTokenRoute,
  ApiV1ScriptsEnhanceRoute: ApiV1ScriptsEnhanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
